/* Tobyn2007 §1: three translation structures, collection, reception versions,
 * and medieval spatial prohibition. These are explicit formal chart predicates. */
(function(root){'use strict';
 const K=['Moon','Mercury','Venus','Sun','Mars','Jupiter','Saturn'],time=e=>Date.parse(e.utc),has=(e,k)=>e.a===k||e.b===k,both=(e,a,b)=>has(e,a)&&has(e,b),any=xs=>xs.includes(true)?true:xs.includes(null)?null:false;
 function evaluate(chart,pairs,future,history){
  const begin=Date.parse(chart.input.utc),past=history.events.filter(e=>time(e)<begin).sort((a,b)=>time(b)-time(a)),events=future.events.filter(e=>time(e)>begin).sort((a,b)=>time(a)-time(b)),p=(a,b)=>pairs.find(e=>both(e,a,b)),orient=x=>x&&root.JYHoraryPerfection.orientation(chart,x),hosts=chart.essentialDignities?.dignityHosting||[];
  function receives(host,guest){return hosts.filter(h=>h.host===host&&h.guest===guest).flatMap(h=>h.dignities.map(dignity=>({dignity})));}
  const first=k=>events.find(e=>has(e,k))||null,last=k=>past.find(e=>has(e,k))||null,direct=(a,b)=>{const x=p(a,b);return x?.phase==='入相'&&orient(x).applicant===a;},mutual=(a,b)=>({[a+'Receives'+b]:receives(a,b),[b+'Receives'+a]:receives(b,a)}),rows=[],collection=[],spatial=[];
  function interrupted(k,start,end,allowed){return future.stations.concat(future.ingresses).filter(e=>e.planet===k&&time(e)>start&&time(e)<end).concat(events.filter(e=>has(e,k)&&time(e)>start&&time(e)<end&&!allowed.some(z=>both(e,...z))));}
  function record(form,A,B,C,conditions,evidence){const vals=Object.values(conditions),status=vals.includes(false)?'not-established':vals.includes(null)?'undetermined':'established',ab=p(A,B),relation=ab?.phase||'no-current-aspect',rec={firstReceivesCarrier:receives(A,C),carrierReceivesSecond:receives(C,B),allDirections:{AC:mutual(A,C),BC:mutual(B,C)}},major=x=>x.some(h=>['sign','exaltation'].includes(h.dignity)),lilly=relation!=='入相';return {form,from:A,to:B,interpositor:C,status,conditions,evidence,significatorRelation:relation,receptions:rec,policies:{lillySeparatingOrNoAspect:{eligible:lilly,status:status==='established'&&!lilly?'not-established':status},bonattiMajorReception:{firstReceivesCarrier:major(rec.firstReceivesCarrier),carrierReceivesSecond:major(rec.carrierReceivesSecond),status:status==='established'&&major(rec.firstReceivesCarrier)&&major(rec.carrierReceivesSecond)?'established':status==='undetermined'?'undetermined':'not-established'}},role:{rulesHouses:chart.houses?chart.houses.cusps.map((v,i)=>root.JYWestern.LORDS[Math.floor(v/30)]===C?i+1:null).filter(Boolean):[],occupies:chart.planets[C].house,essentialDignities:chart.essentialDignities?.planets?.find(e=>e.planet===C)||null},remaining:'形式與具名接納政策分列；介入星所代表的現實人物／事情是否助阻需合原題，不能由宮號自動認定。'};}
  for(const C of K)for(const A of K)for(const B of K){if(new Set([A,B,C]).size!==3)continue;
   const ac=p(A,C),bc=p(B,C),lc=last(C),fc=first(C),fa=first(A),cb=events.find(e=>both(e,C,B)),ca=events.find(e=>both(e,C,A)),speed=k=>Math.abs(chart.planets[k].speed);
   // Swift carrier: the LAST contact must be A, and the NEXT must be B.
   if(ac?.phase==='出相'&&bc?.phase==='入相')rows.push(record('type1-last-separation-next-application',A,B,C,{carrierFaster:speed(C)>speed(A)&&speed(C)>speed(B),sourceInCurrentSeparatingOrb:true,sourceIsLastContact:lc?both(lc,A,C):null,targetIsNextContact:fc?both(fc,B,C):null,carrierAppliesToTarget:direct(C,B),uninterrupted:cb?interrupted(C,begin,time(cb),[]).length===0:null}, {last:lc,next:fc,departing:ac,applying:bc}));
   // Carrier receives A's first application, then carries it to B.
   if(direct(A,C)&&direct(C,B)){
    const next=ca?events.find(e=>has(e,C)&&time(e)>time(ca)):null;
    rows.push(record('type2-receive-then-carry',A,B,C,{sourceFirstToCarrier:fa?both(fa,A,C):null,carrierFirstContactSource:fc?both(fc,A,C):null,carrierNextToTarget:next?both(next,C,B):null,contactOrder:ca&&cb?time(ca)<time(cb):null,uninterrupted:ca&&cb?interrupted(C,begin,time(cb),[[A,C]]).length===0:null},{source:ca,target:cb,carrierNextAfterSource:next}));
   }
   // Carrier already separates from B, faster A receives carried light by catching C.
   if(bc?.phase==='出相'&&direct(A,C))rows.push(record('type2-caught-carrier',B,A,C,{sourceIsLastContact:lc?both(lc,B,C):null,targetFirstToCarrier:fa?both(fa,A,C):null,carrierNextIsTarget:fc?both(fc,A,C):null,sourceInCurrentSeparatingOrb:true,uninterrupted:ca?interrupted(C,begin,time(ca),[]).length===0:null},{last:lc,next:fc,source:bc,target:ac}));
  }
  for(let i=0;i<K.length;i++)for(let j=i+1;j<K.length;j++)for(const C of K){const A=K[i],B=K[j];if(C===A||C===B||!direct(A,C)||!direct(B,C))continue;
   const a=first(A),b=first(B),ca=events.find(e=>both(e,A,C)),cb=events.find(e=>both(e,B,C)),ordered=[ca,cb].filter(Boolean).sort((x,y)=>time(x)-time(y)),end=ordered.length===2?time(ordered[1]):null,recFirst=ordered[0]?(has(ordered[0],A)?A:B):null,recSecond=recFirst===A?B:A;
   const row=record('collection-first-applications',A,B,C,{collectorSlower:Math.abs(chart.planets[C].speed)<Math.abs(chart.planets[A].speed)&&Math.abs(chart.planets[C].speed)<Math.abs(chart.planets[B].speed),firstA:a?both(a,A,C):null,firstB:b?both(b,B,C):null,bothContacts:ca&&cb?true:null,collectorUninterrupted:end?interrupted(C,begin,end,[[A,C],[B,C]]).length===0:null}, {orderedContacts:ordered,firstA:a,firstB:b});
   const firstReception=recFirst?receives(C,recFirst):[],secondReception=recFirst?receives(recSecond,C):[];
   row.collectionReceptions={collectorReceivesFirst:firstReception,secondReceivesCollector:secondReception};row.policies.bonattiMajorReception={firstReceivesCarrier:firstReception.length>0,carrierReceivesSecond:secondReception.length>0,status:row.status==='established'&&firstReception.some(h=>['sign','exaltation'].includes(h.dignity))&&secondReception.some(h=>['sign','exaltation'].includes(h.dignity))?'established':row.status==='undetermined'?'undetermined':'not-established'};collection.push(row);
  }
  for(const ab of pairs.filter(x=>x.phase==='入相')){const o=orient(ab),A=o.applicant,B=o.receiver,near=[];for(const C of K.filter(k=>![A,B].includes(k))){const cb=p(C,B);if(cb?.phase!=='入相'||orient(cb).applicant!==C)continue;const d=cb.orb,base=ab.orb,equal=Math.abs(d-base)<1e-7,closer=d<base-1e-7,strongerAtEqual=equal&&cb.angle===0&&ab.angle!==0;near.push({interpositor:C,spatialDistance:d,applicantDistance:base,equidistant:equal,conjunctionPriority:strongerAtEqual,status:closer||strongerAtEqual?'established':equal?'undetermined':'not-established',reception:mutual(C,B),temporalContact:events.find(e=>both(e,C,B))||null,missing:equal&&!strongerAtEqual?['原典未給非合相間完整階序與接納同級裁決，保留等距']:[]});}spatial.push({pair:[A,B],angle:ab.angle,profile:'ABU_MASHAR_BONATTI_SPATIAL_PLUS_CONJUNCTION_PRIORITY',checks:near});}
  return {version:'20261003light1',status:'calculated',historyWindow:{start:history.start,endExclusive:history.endExclusive},futureWindow:{start:future.start,endExclusive:future.endExclusive},translations:rows,collections:collection,spatialProhibition:spatial,source:'https://www.skyscript.co.uk/tobyn2.html',policy:'全七曜依实际星曆核最後分離、首次成相、換座與駐留；有限窗不足標未定。Lilly本命兩主星非入相政策、Bonatti接納版本與一般幾何分列。中世紀距成相度數及等距合相優先獨立核算，不拿未來時間代替。'};
 }
 root.JYHoraryLight=Object.freeze({evaluate,version:'20261003light1'});
})(typeof window==='undefined'?globalThis:window);
