/* Da Liu Ren class rules, independently formalised from 六壬大全 課經集卷七至十.
 * Every decision has its tested conditions, edition and missing inputs.
 * 三-valued logic is intentional: absent 年命/calendar data is never false evidence.
 */
(function(root){
 'use strict';
 var VERSION='20261003liurenclasses1',G=Array.from('甲乙丙丁戊己庚辛壬癸'),B=Array.from('子丑寅卯辰巳午未申酉戌亥'),E=['木','火','土','金','水'];
 var GE=[0,0,1,1,2,2,3,3,4,4],BE=[4,2,0,0,2,1,1,2,3,3,2,4],JI=[2,4,5,7,5,7,8,10,11,1],LU=[2,3,5,6,5,6,8,9,11,0],MA=[2,11,8,5,2,11,8,5,2,11,8,5];
 var X=[3,10,5,0,4,8,6,1,2,9,7,11],HARM=[7,6,5,4,3,2,1,0,11,10,9,8],BREAK=[9,4,11,6,1,8,3,10,5,0,7,2],HE=[1,0,11,10,9,8,7,6,5,4,3,2];
 var DE=[2,8,5,11,5,2,8,5,11,5],MUB=[7,10,4,1,4],SHENG=[11,2,8,5,8],WANG=[3,6,6,9,0],JG=[2,1,1,0,2,0,2,3,2,4,3,4];
 var GOOD=[0,3,5,8,10,11],TRI=[[8,0,4],[11,3,7],[2,6,10],[5,9,1]],ZHONG=[0,3,6,9],MENG=[2,5,8,11],JIQU=[1,4,7,10];
 var MANSIONS=Array.from('角亢氐房心尾箕斗牛女虛危室壁奎婁胃昴畢觜參井鬼柳星張翼軫'),START=[12,14,16,18,20,22,25,0,2,4,7,10],REPEAT=[14,25,21,26,2,7];
 var MANSION_BRANCH=[4,4,3,3,3,2,2,1,1,0,0,0,11,11,10,10,9,9,9,8,8,7,7,6,6,6,5,5];
 var FORWARD=['向陽','出戶','出陽','盈陽','登三天','充盈','出三天','入冥','涉三淵','凝陰','入三淵','溟濛'],BACKWARD=['偃蹇','極陰','冥陰','斷澗','涉疑','轉悖','顧祖','回明','凝陽','勵明','悖戾','時遁'];
 function mod(n,m){return (n%m+m)%m;}function bi(x){return typeof x==='number'&&x>=0&&x<12&&Number.isInteger(x)?x:B.indexOf(x);}
 function ke(a,b){return mod(a+2,5)===b;}function sheng(a,b){return mod(a+1,5)===b;}
 function all(a){return a.includes(false)?false:a.includes(null)?null:true;}function any(a){return a.includes(true)?true:a.includes(null)?null:false;}
 function c(label,value,facts,missing){return {condition:label,value:value==null?null:!!value,facts:facts==null?null:facts,missing:value==null?(missing||[]):[]};}
 function tri(a,b){return a!==b&&TRI.some(function(t){return t.includes(a)&&t.includes(b);});}function he(a,b){return HE[a]===b||tri(a,b);}
 function fullTri(t){return new Set(t).size===3&&TRI.some(function(a){return t.every(function(b){return a.includes(b);});});}
 function seasonal(e,month,context){if(month==null)return null;var m=context&&Number.isInteger(context.seasonElementIndex)?context.seasonElementIndex:BE[month];return e===m?'旺':sheng(m,e)?'相':sheng(e,m)?'休':ke(e,m)?'囚':'死';}
 function lunarMansion(month,day){
  month=Math.abs(Number(month));day=Number(day);if(!Number.isInteger(month)||month<1||month>12||!Number.isInteger(day)||day<1||day>30)return null;
  var at=START[month-1],remain=day-1;while(remain>0){var span=REPEAT.includes(at)?2:1;if(remain<span)break;remain-=span;at=mod(at+1,28);}
  return {mansion:MANSIONS[at],index:at,branch:B[MANSION_BRANCH[at]],branchIndex:MANSION_BRANCH[at],lunarMonth:month,lunarDay:day,profile:'課經二煩起宿歌；奎張井翼氐斗各重留一日；十月用心宿',astronomicalPosition:false};
 }
 function annual(p){
  p=p||{};if(p.natalBranch&&bi(p.natalBranch)<0)throw new Error('本命地支無效。');if(p.annualBranch&&bi(p.annualBranch)<0)throw new Error('行年地支無效。');if(p.annualGan&&G.indexOf(p.annualGan)<0)throw new Error('行年天干無效。');if(p.virtualAge!=null&&p.virtualAge!==''&&(!Number.isInteger(Number(p.virtualAge))||Number(p.virtualAge)<1||Number(p.virtualAge)>150))throw new Error('虛歲須是1至150的整數。');if(p.annualDirection&&!['male','female'].includes(p.annualDirection))throw new Error('行年起法無效。');var natal=bi(p.natalBranch),a=bi(p.annualBranch),gan=G.indexOf(p.annualGan),age=Number(p.virtualAge),mode=p.annualDirection;
  if(a<0&&Number.isInteger(age)&&age>=1&&age<=150&&(mode==='male'||mode==='female')){var step=mode==='male'?age-1:1-age;a=mod((mode==='male'?2:8)+step,12);gan=mod((mode==='male'?2:8)+step,10);}
  if(a>=0&&gan>=0&&a%2!==gan%2)throw new Error('行年干支陰陽不合。');
  return {label:String(p.label||'占人'),natalBranch:natal<0?null:B[natal],natalIndex:natal<0?null:natal,annualBranch:a<0?null:B[a],annualIndex:a<0?null:a,annualGan:gan<0?null:G[gan],annualGanIndex:gan<0?null:gan,virtualAge:Number.isInteger(age)&&age>0?age:null,annualDirection:mode==='male'||mode==='female'?mode:null,source:a<0?'未提供':p.annualBranch?'使用者明示行年':'觀月經：男一歲丙寅順行、女一歲壬申逆行；虛歲由使用者明示'};
 }
 function compute(r,context,people){
  function seasonAt(e,month){return seasonal(e,month,context);}
  context=context||r.calendarContext||{};people=people||r.participants||[];var participants=people.map(annual),g=G.indexOf(r.day.gan),d=B.indexOf(r.day.zhi),res=JI[g],de=GE[g],db=BE[d],t=r.transmissions.map(function(x){return x.branchIndex;}),f=t[0],mid=t[1],last=t[2],co=r.courses,up=co.map(function(x){return x.upperIndex;}),gu=co.map(function(x){return x.generalIndex;}),gen=r.transmissions.map(function(x){return x.generalIndex;}),yr=bi(context.yearBranch),mo=bi(context.monthBranch);
  if(yr<0)yr=null;if(mo<0)mo=null;var mp=mo==null?null:mod(mo-2,12),season=mo==null?null:Math.floor(mod(mo-2,12)/3),xun=B.indexOf(r.xun.head.slice(1)),tail=mod(xun+9,12),dayDe=DE[g],zhiDe=mod(d+5,12),mansion=lunarMansion(context.lunarMonth,context.lunarDay),checks=[],p=participants[0]||annual({}),q=participants[1]||annual({});
  function sky(b){return b==null?null:mod(b+r.rotation,12);}function earth(b){return b==null?null:mod(b-r.rotation,12);}function good(n){return GOOD.includes(n);}function general(b){return b==null?null:r.plate.find(function(x){return x.skyIndex===b;}).generalIndex;}
  function active(e){var s=seasonAt(e,mo);return s==null?null:s==='旺'||s==='相';}function dormant(e){var s=seasonAt(e,mo);return s==null?null:s==='囚'||s==='死';}
  function atRef(b){return any([earth(b)===res,earth(b)===d,p.natalIndex==null?null:earth(b)===p.natalIndex,p.annualIndex==null?null:earth(b)===p.annualIndex]);}
  function peGood(z){return z.natalIndex==null||z.annualIndex==null?null:good(general(sky(z.natalIndex)))&&good(general(sky(z.annualIndex)));}
  function match(name,vol,variants,details){
   var vs=variants.map(function(v){var val=all(v.conditions.map(function(x){return x.value;}));return {name:v.name||'課經正文',value:val,conditions:v.conditions};}),val=any(vs.map(function(v){return v.value;}));
   var missing=Array.from(new Set(vs.filter(function(v){return v.value===null;}).flatMap(function(v){return v.conditions.flatMap(function(x){return x.missing;});})));
   checks.push({id:checks.length+1,name:name,status:val===true?'established':val===false?'not-established':'insufficient-data',established:val,variants:vs,missing:missing,details:details||{},source:{work:'六壬大全·課經集',volume:vol,url:'https://zh.wikisource.org/zh-hant/六壬大全/'+vol,section:name+'課'}});
  }
  function one(name,vol,conds,details){match(name,vol,[{conditions:conds}],details);}
  function v(name,conds){return {name:name,conditions:conds};}function z(label,value,facts){return c(label,value,facts,['節氣月建']);}
  var gates=['元首','重審','知一','涉害','遙克','昴星','別責','八專','伏吟','返吟'];
  gates.forEach(function(n){var value=n==='元首'?r.method.gate==='賊剋'&&r.method.type==='元首':n==='重審'?r.method.gate==='賊剋'&&r.method.type==='重審':n==='知一'?r.method.gate==='比用':n==='涉害'?r.method.gate==='涉害':n==='遙克'?r.method.gate==='遙剋':n==='伏吟'?r.rotation===0:n==='返吟'?r.rotation===6:r.method.gate===n;one(n,7,[c('九宗門實際取傳及天地盤',value,{gate:r.method.gate,type:r.method.type,rotation:r.rotation,selectedCourses:r.method.selectedCourses,depths:r.method.depths,trace:r.method.trace})]);});
  one('三光',7,[z('日干、日支及初傳俱旺相',all([active(de),active(db),active(BE[f])]),[r.day.gan,r.day.zhi,B[f]].map(function(b,i){return {symbol:b,state:seasonAt([de,db,BE[f]][i],mo)};})),c('干上、支上及初傳皆乘吉將',good(gu[0])&&good(gu[2])&&good(gen[0]),[co[0].general,co[2].general,r.transmissions[0].general])]);
  one('三陽',7,[c('貴人順布、日辰居貴前',r.noble.direction==='順布'&&gu[0]>=1&&gu[0]<=5&&gu[2]>=1&&gu[2]<=5,{direction:r.noble.direction,dayGeneralIndex:gu[0],branchGeneralIndex:gu[2]}),z('訂訛：初傳旺相',active(BE[f]),{month:mo==null?null:B[mo],firstState:seasonAt(BE[f],mo)})],{nobleFront:'順逆布將後的貴人至青龍前半盤，不把天空至天后當貴前',edition:'採訂訛貴順、日辰居前、發用旺相三項；正文乙丑春占算例，不把丑土死氣誤當排除條件'});
  var qi=xun===0||xun===10?1:xun===8||xun===6?0:11,riqi=[6,5,4,3,2,1,7,8,9,10][g],zhiyi=[6,5,4,3,2,1,7,8,9,10,11,0][d];
  match('三奇',7,[v('旬奇',[c('旬奇入三傳',t.includes(qi),{xun:r.xun.head,qi:B[qi],transmissions:t.map(function(b){return B[b];})})]),v('日奇',[c('日奇入三傳',t.includes(riqi),{day:r.day.gan,qi:B[riqi]})])]);
  match('六儀',7,[v('旬首六儀',[c('旬首入三傳',t.includes(xun),{head:r.xun.head})]),v('支儀',[c('支儀入三傳',t.includes(zhiyi),{day:r.day.zhi,yi:B[zhiyi]})])]);
  one('時泰',7,[c('初傳為太歲或月建',any([yr==null?null:f===yr,mo==null?null:f===mo]),{first:B[f],year:yr==null?null:B[yr],month:mo==null?null:B[mo]},['太歲與月建']),c('初乘青龍或六合',gen[0]===5||gen[0]===3,r.transmissions[0].general),c('初傳作日財或日辰德',ke(de,BE[f])||f===dayDe||f===zhiDe,{kinship:r.transmissions[0].kinship,dayDe:B[dayDe],branchDe:B[zhiDe]})]);
  one('龍德',7,[c('太歲與月將俱為初傳',yr==null?null:f===yr&&f===B.indexOf(r.monthGeneral.branch),{year:yr==null?null:B[yr],monthGeneral:r.monthGeneral.branch,first:B[f]},['太歲']),c('初傳乘天乙貴人',gen[0]===0,r.transmissions[0].general)]);
  var horses=[MA[d],mo==null?null:MA[mo],yr==null?null:MA[yr],p.natalIndex==null?null:MA[p.natalIndex],p.annualIndex==null?null:MA[p.annualIndex]];
  one('官爵',8,[c('歲月日或年命驛馬發用',any(horses.map(function(b){return b==null?null:b===f;})),horses.map(function(b){return b==null?null:B[b];}),['太歲、月建或占人年命']),c('三傳有天魁戌及太常',t.includes(10)&&gen.includes(8),{transmissions:t.map(function(b){return B[b];}),generals:r.transmissions.map(function(x){return x.general;})})]);
  one('富貴',8,[c('貴人發用',gen[0]===0,r.transmissions[0].general),z('貴人旺相',active(BE[f]),seasonAt(BE[f],mo)),c('初傳上下相生',sheng(BE[f],BE[earth(f)])||sheng(BE[earth(f)],BE[f]),{upper:B[f],lower:B[earth(f)]}),c('貴人臨干支年命',atRef(f),{earth:B[earth(f)],dayResidence:B[res],dayBranch:B[d],participant:p},['占人年命'])]);
  one('軒蓋',8,[c('午發用、三傳見卯子',f===6&&t.includes(3)&&t.includes(0),t.map(function(b){return B[b];}))]);
  one('鑄印',8,[c('中傳戌臨地盤巳',mid===10&&earth(mid)===5,{middle:B[mid],earth:B[earth(mid)]})]);
  one('斫輪',8,[c('卯發用臨庚申或辛戌寄宮',f===3&&(earth(f)===8||earth(f)===10),{first:B[f],earth:B[earth(f)]})]);
  match('引從',8,[v('引從干上',[c('初末夾干上神',f===mod(up[0]+1,12)&&last===mod(up[0]-1,12),{first:B[f],dayUpper:B[up[0]],last:B[last]})]),v('引從支上',[c('初末夾支上神',f===mod(up[2]+1,12)&&last===mod(up[2]-1,12),{first:B[f],branchUpper:B[up[2]],last:B[last]})])]);
  match('亨通',8,[v('初傳生日',[c('初傳五行生日干',sheng(BE[f],de),[E[BE[f]],E[de]])]),v('順遞生',[c('初生中、中生末、末生日',sheng(BE[f],BE[mid])&&sheng(BE[mid],BE[last])&&sheng(BE[last],de),t.map(function(b){return E[BE[b]];}).concat(E[de]))]),v('逆遞生',[c('末生中、中生初、初生日',sheng(BE[last],BE[mid])&&sheng(BE[mid],BE[f])&&sheng(BE[f],de),[last,mid,f].map(function(b){return E[BE[b]];}).concat(E[de]))]),v('干支俱生',[c('干上生日、支上生支',sheng(BE[up[0]],de)&&sheng(BE[up[2]],db),up.map(function(b){return B[b];}))]),v('干支互生',[c('干上生支、支上生日',sheng(BE[up[0]],db)&&sheng(BE[up[2]],de),up.map(function(b){return B[b];}))]),v('干支俱旺',[c('干支上神分別為各自帝旺支',up[0]===WANG[de]&&up[2]===WANG[db],{dayWang:B[WANG[de]],branchWang:B[WANG[db]]})]),v('干支互旺',[c('干支上神互為對方帝旺支',up[0]===WANG[db]&&up[2]===WANG[de],{dayWang:B[WANG[de]],branchWang:B[WANG[db]]})])]);
  var pairReady=p.annualIndex!=null&&q.annualIndex!=null,pa=sky(p.annualIndex),qa=sky(q.annualIndex),pairNatal=p.natalIndex!=null&&q.natalIndex!=null;
  match('繁昌',8,[v('德孕格',[c('兩人行年干合支合',pairReady&&p.annualGanIndex!=null&&q.annualGanIndex!=null?mod(p.annualGanIndex+5,10)===q.annualGanIndex&&HE[p.annualIndex]===q.annualIndex:null,[p,q],['兩人完整行年干支']),c('兩人年上神乘本命旺相五行',pairReady&&pairNatal?(BE[pa]===BE[p.natalIndex]||sheng(BE[p.natalIndex],BE[pa]))&&(BE[qa]===BE[q.natalIndex]||sheng(BE[q.natalIndex],BE[qa])):null,{yearUppers:[pa,qa].map(function(b){return b==null?null:B[b];}),participants:[p,q]},['兩人本命與行年'])]),v('旺孕格',[c('兩人行年異位同三合',pairReady?tri(p.annualIndex,q.annualIndex):null,[p.annualBranch,q.annualBranch],['兩人行年']),z('兩人行年俱居時令旺相',pairReady?all([active(BE[p.annualIndex]),active(BE[q.annualIndex])]):null,{month:mo==null?null:B[mo],participants:[p,q]})])],{historicalTerm:'只表示課經條件，不判定懷孕、胎兒性別或生育結果'});
  one('榮華',8,[c('祿馬貴俱臨干支年命或入傳',all([any([t.includes(LU[g]),atRef(LU[g])]),any([t.includes(MA[d]),atRef(MA[d])]),any([gen.includes(0),atRef(B.indexOf(r.noble.branch))])]),{lu:B[LU[g]],horse:B[MA[d]],noble:r.noble.branch,participants:participants},['占人年命']),z('初傳旺相',active(BE[f]),seasonAt(BE[f],mo)),c('初傳乘吉將',good(gen[0]),r.transmissions[0].general)]);
  var TD=mp==null?null:['丁','申','壬','辛','亥','甲','癸','寅','丙','乙','巳','庚'][mp],tdb=TD==null?null:B.includes(TD)?B.indexOf(TD):JI[G.indexOf(TD)],MD=mo==null?null:[2,6,10].includes(mo)?2:[11,3,7].includes(mo)?0:[8,0,4].includes(mo)?8:6,mdb=MD==null?null:JI[MD];
  one('德慶',8,[c('日德、支德、天德或月德發用',any([f===dayDe,f===zhiDe,tdb==null?null:f===tdb,mdb==null?null:f===mdb]),{dayDe:B[dayDe],branchDe:B[zhiDe],tianDe:TD,tianDeResidence:tdb==null?null:B[tdb],yueDe:MD==null?null:G[MD],yueDeResidence:mdb==null?null:B[mdb]},['節氣月建']),c('占人年命乘吉將',peGood(p),p,['占人本命與行年'])]);
  one('合歡',8,[c('干上遁干五合或干上五合干寄宮',co[0].hiddenStem!=null&&G.indexOf(co[0].hiddenStem)===mod(g+5,10)||up[0]===JI[mod(g+5,10)],{day:r.day.gan,upper:co[0].branch,hiddenStem:co[0].hiddenStem,partnerStem:G[mod(g+5,10)],partnerResidence:B[JI[mod(g+5,10)]]}),c('支三合六合發用',he(f,d)||fullTri(t)&&t.includes(d),{first:B[f],branch:B[d],transmissions:t.map(function(b){return B[b];})}),c('占人年命俱乘吉將',peGood(p),p,['占人本命與行年'])]);
  match('和美',8,[v('上下合',[c('干上與寄宮合、支上與支合',he(up[0],res)&&he(up[2],d),{dayUpper:B[up[0]],dayResidence:B[res],branchUpper:B[up[2]],dayBranch:B[d]})]),v('交互合',[c('干支上神六合或干支上下交合',HE[up[0]]===up[2]||he(up[0],d)&&he(up[2],res),up.map(function(b){return B[b];}))]),v('傳三合相呼',[c('三傳三合、干支上六合或生日作財',fullTri(t)&&(HE[up[0]]===up[2]||sheng(BE[up[0]],de)||ke(de,BE[up[0]])||sheng(BE[up[2]],de)||ke(de,BE[up[2]])),{transmissions:t.map(function(b){return B[b];}),uppers:up.map(function(b){return B[b];})})])]);
  one('斬關',8,[c('辰戌臨日辰發用',(f===4||f===10)&&(earth(f)===res||earth(f)===d),{first:B[f],earth:B[earth(f)]})]);
  match('閉口',8,[v('旬尾加旬首',[c('旬尾加旬首發用',f===tail&&earth(f)===xun,{head:B[xun],tail:B[tail],first:B[f],earth:B[earth(f)]})]),v('旬首玄武',[c('旬首乘玄武發用',f===xun&&gen[0]===9,{head:B[xun],first:r.transmissions[0]})]),v('旬首上玄武',[c('地盤旬首上神乘玄武發用',earth(f)===xun&&gen[0]===9,{head:B[xun],first:r.transmissions[0]})])]);
  var tm=mp==null?null:mod(6+2*mp,12);
  one('遊子',9,[c('三傳俱季土',t.every(function(b){return JIQU.includes(b);}),t.map(function(b){return B[b];})),c('初傳旬丁或天馬',any([r.transmissions[0].hiddenStem==='丁',tm==null?null:f===tm]),{hiddenStem:r.transmissions[0].hiddenStem,tianMa:tm==null?null:B[tm]},['節氣月建'])]);
  one('三交',9,[c('仲日、仲加支、三傳皆仲',ZHONG.includes(d)&&ZHONG.includes(up[2])&&t.every(function(b){return ZHONG.includes(b);}),{day:B[d],branchUpper:B[up[2]],transmissions:t.map(function(b){return B[b];})}),c('傳乘太陰或六合',gen.includes(10)||gen.includes(3),r.transmissions.map(function(x){return x.general;}))],{withoutGenerals:'只有前項而缺陰合，另記為三交不交，不混同完整三交'});
  one('贅婿',9,[c('日干克日支',ke(de,db),[E[de],E[db]]),c('干臨支或支臨干發用',earth(res)===d&&f===res||earth(d)===res&&f===d,{first:B[f],dayResidence:B[res],dayBranch:B[d],residenceEarth:B[earth(res)],branchEarth:B[earth(d)]})]);
  one('衝破',9,[c('日辰沖神發用',(f===mod(res+6,12)||f===mod(d+6,12)),{first:B[f],dayResidence:B[res],dayBranch:B[d]}),c('初傳上下相破',BREAK[f]===earth(f),{upper:B[f],earth:B[earth(f)]})]);
  match('淫泆',9,[v('卯酉后合',[c('卯酉發用乘天后或六合',(f===3||f===9)&&(gen[0]===11||gen[0]===3),r.transmissions[0])]),v('狡童格',[c('初合末后',gen[0]===3&&gen[2]===11,r.transmissions.map(function(x){return x.general;}))]),v('泆女格',[c('初后末合',gen[0]===11&&gen[2]===3,r.transmissions.map(function(x){return x.general;}))])],{historicalTerm:'不得據課名推斷性行為、忠誠或他人品行'});
  var distinct=new Set(up).size,upperKe=co.filter(function(x){return x.relation==='上剋下';}).length,lowerKe=co.filter(function(x){return x.relation==='下賊上';}).length;
  match('蕪淫',9,[v('三課有克',[c('三課不備且有克',distinct===3&&(upperKe+lowerKe)>0,{distinctCourses:distinct,upperKe:upperKe,lowerKe:lowerKe})]),v('交互克',[c('干支上神交互克日辰',ke(BE[up[2]],de)&&ke(BE[up[0]],db),up.map(function(b){return B[b];}))]),v('觀月經別責亦蕪淫',[c('九宗門別責',r.method.gate==='別責',r.method)])]);
  match('解離',9,[v('干支解離',[c('日干克支上、日支克干上',ke(de,BE[up[2]])&&ke(db,BE[up[0]]),{day:r.day.ganzhi,uppers:up.map(function(b){return B[b];})})]),v('兩人行年交克',[c('兩行年交互克上神',pairReady?ke(BE[p.annualIndex],BE[qa])&&ke(BE[q.annualIndex],BE[pa]):null,{participants:[p,q],uppers:[pa,qa].map(function(b){return b==null?null:B[b];})},['兩人行年'])]),v('兩人行年相沖',[c('兩行年六沖',pairReady?mod(p.annualIndex+6,12)===q.annualIndex:null,[p,q],['兩人行年'])])]);
  var solitary=season==null?null:[[5,6],[8,9],[11,0],[2,3]][season],widow=season==null?null:[[0,1],[3,4],[6,7],[9,10]][season];
  match('孤寡',9,[v('旬空孤寡',[c('初傳或所臨地盤旬空',r.transmissions[0].empty||r.xun.empty.includes(B[earth(f)]),{first:r.transmissions[0],empty:r.xun.empty})]),v('袖中金時令孤寡',[z('孤寡季位入三傳',season==null?null:t.some(function(b){return solitary.includes(b)||widow.includes(b);}),{season:season,solitary:solitary&&solitary.map(function(b){return B[b];}),widow:widow&&widow.map(function(b){return B[b];})})])]);
  one('度厄',9,[c('四課恰有三上克下或三下賊上',upperKe===3||lowerKe===3,{upperKe:upperKe,lowerKe:lowerKe,courses:co.map(function(x){return x.relation;})})]);
  match('無祿絕嗣',9,[v('正文無祿',[c('四課俱上克下',upperKe===4,co.map(function(x){return x.relation;}))]),v('正文絕嗣',[c('四課俱下賊上',lowerKe===4,co.map(function(x){return x.relation;}))])],{editionDifference:'本卷正文與訂訛對無祿、絕嗣兩名的配對相反，本版保留正文及實際克向'});
  var bads=[z('初傳時令死氣',mo==null?null:seasonAt(BE[f],mo)==='死',{first:B[f],state:seasonAt(BE[f],mo)}),z('初傳受旺地盤克',mo==null?null:seasonAt(BE[earth(f)],mo)==='旺'&&ke(BE[earth(f)],BE[f]),{sky:B[f],earth:B[earth(f)]}),c('仰見地盤五行之墓',f===MUB[BE[earth(f)]],{sky:B[f],earth:B[earth(f)],earthElementTomb:B[MUB[BE[earth(f)]]]}),c('俯受地盤克',ke(BE[earth(f)],BE[f]),{sky:B[f],earth:B[earth(f)]}),c('初乘凶將',!good(gen[0]),r.transmissions[0].general),c('傳逢刑害或子墳墓星',X[f]===mid||HARM[f]===mid||X[mid]===last||HARM[mid]===last||t.includes(0),t.map(function(b){return B[b];})),c('傳有下賊上',t.some(function(b){return ke(BE[earth(b)],BE[b]);}),r.transmissions.map(function(x){return {sky:x.branch,earth:x.earth};})),c('凶將臨日辰並克下',!good(gu[0])&&ke(BE[up[0]],de)||!good(gu[2])&&ke(BE[up[2]],db),[co[0],co[2]])];
  var bless=[z('初死末旺相',all([mo==null?null:seasonAt(BE[f],mo)==='死',active(BE[last])]),[f,last].map(function(b){return {branch:B[b],state:seasonAt(BE[b],mo)};})),c('末生初而帶德解救',sheng(BE[last],BE[f])&&(last===dayDe||last===zhiDe||good(gen[2])),{first:B[f],last:B[last],general:r.transmissions[2].general,dayDe:B[dayDe],branchDe:B[zhiDe]}),c('初凶將末吉將',!good(gen[0])&&good(gen[2]),[r.transmissions[0].general,r.transmissions[2].general]),c('初鬼得年命上神克制',ke(BE[f],de)?any([p.natalIndex==null?null:ke(BE[sky(p.natalIndex)],BE[f]),p.annualIndex==null?null:ke(BE[sky(p.annualIndex)],BE[f])]):false,{first:r.transmissions[0],participant:p},['占人年命']),z('干上吉將且旺相',all([good(gu[0]),active(BE[up[0]])]),co[0])];
  one('迍福',9,[c('八迍至少一項',any(bads.map(function(x){return x.value;})),bads,['節氣月建']),c('五福至少一項',any(bless.map(function(x){return x.value;})),bless,['節氣月建或占人年命'])],{eightObstructions:bads,fiveResolutions:bless,quantifier:'課經算例未具全八項仍稱迍福；逐項列出，不虛稱八迍五福全具'});
  match('侵害',9,[v('干支六害發用',[c('六害臨干支發用',HARM[f]===earth(f)&&(earth(f)===res||earth(f)===d),r.transmissions[0])]),v('行年六害發用',[c('六害臨行年發用',p.annualIndex==null?null:HARM[f]===earth(f)&&earth(f)===p.annualIndex,{first:r.transmissions[0],participant:p},['占人行年'])])]);
  match('刑傷',9,[v('課內刑神發用',[c('初傳與課下形成刑',f===X[d]||f===X[res]||co.some(function(x){return x.upperIndex===f&&X[x.lowerBranch]===f;}),co.map(function(x){return {lower:x.lower,upper:x.upper};}))]),v('行年受刑',[c('刑神臨行年發用',p.annualIndex==null?null:X[p.annualIndex]===f&&earth(f)===p.annualIndex,{first:r.transmissions[0],participant:p},['占人行年'])])]);
  var ld=Number(context.lunarDay),lc=Number(context.lunarDayCount),quarters=Number.isInteger(ld)&&ld>0?(ld===1||ld===8||ld===15||ld===23||(Number.isInteger(lc)&&ld===lc)):null,moon=mansion&&mansion.branchIndex;
  var commonFan=[c('月將四仲',ZHONG.includes(B.indexOf(r.monthGeneral.branch)),r.monthGeneral),c('四正仲日',ZHONG.includes(d),r.day.ganzhi),c('朔弦望晦',quarters,{lunarDay:context.lunarDay,lunarDayCount:context.lunarDayCount},['農曆日與月天數']),c('天罡斗繫丑未',earth(4)===1||earth(4)===7,{earth:B[earth(4)]})];
  match('二煩',9,[v('天煩',commonFan.concat(c('月將宿臨四仲發用',f===B.indexOf(r.monthGeneral.branch)&&ZHONG.includes(earth(f)),r.transmissions[0]))),v('地煩',commonFan.concat(c('古法月宿臨四仲發用',moon==null?null:f===moon&&ZHONG.includes(earth(moon)),mansion,['農曆月日'])))],{lunarMansion:mansion,calendarPolicy:'按二煩起宿歌推古法月宿；不偽稱天文實測月球赤經或二十八宿界距'});
  var yg=G.indexOf(context.previousDayGan),yd=bi(context.previousDayBranch),yres=yg<0?null:JI[yg];if(yd<0)yd=null;
  one('天禍',9,[c('四立當日',typeof context.fourStarts==='boolean'?context.fourStarts:null,context.solarDayEvents,['四立曆日']),c('今日干支臨昨日干支或反臨',yres==null||yd==null?null:earth(res)===yres&&earth(d)===yd||earth(yres)===res&&earth(yd)===d,{today:r.day.ganzhi,yesterday:context.previousDayGan&&context.previousDayBranch?context.previousDayGan+context.previousDayBranch:null},['前一日起課時段的日干支'])]);
  one('天獄',9,[c('天罡辰繫日干長生',earth(4)===SHENG[de],{earth:B[earth(4)],longsheng:B[SHENG[de]]}),c('初傳囚死或日墓',any([dormant(BE[f]),f===MUB[de]]),{first:B[f],state:seasonAt(BE[f],mo),tomb:B[MUB[de]]},['節氣月建'])]);
  match('天寇',9,[v('正文四離日',[c('分至前一日',typeof context.fourSeparations==='boolean'?context.fourSeparations:null,context.solarDayEvents,['四離曆日']),c('古法月宿加該離日支',moon==null?null:earth(moon)===d,{moon:mansion,dayBranch:B[d]},['農曆月日'])]),v('訂訛分至日望前一日',[c('分至當日',typeof context.fourCardinals==='boolean'?context.fourCardinals:null,context.solarDayEvents,['分至曆日']),c('古法月宿加前一日離辰',moon==null||yd==null?null:earth(moon)===yd,{moon:mansion,previousBranch:yd==null?null:B[yd]},['農曆月日及前一日日支'])])],{editionDifference:'正文說四離日，訂訛及算例在分至日取前一日為離辰；兩套分列'});
  one('天網',9,[c('占時克日干、初傳亦克日干',ke(BE[B.indexOf(r.hourBranch)],de)&&ke(BE[f],de),{hour:r.hourBranch,first:B[f],day:r.day.gan})]);
  var deadSpirit=mp==null?null:mod(5+mp,12),deadQi=mp==null?null:mod(6+mp,12);
  one('魄化',9,[c('初乘白虎',gen[0]===7,r.transmissions[0].general),z('初傳月死神或死氣',mp==null?null:f===deadSpirit||f===deadQi,{deadSpirit:deadSpirit==null?null:B[deadSpirit],deadQi:deadQi==null?null:B[deadQi]}),c('初傳臨干支行年',any([earth(f)===res,earth(f)===d,p.annualIndex==null?null:earth(f)===p.annualIndex]),r.transmissions[0],['占人行年'])]);
  one('三陰',9,[c('貴逆且日辰居貴後',r.noble.direction==='逆布'&&gu[0]>=6&&gu[2]>=6,{direction:r.noble.direction,generalIndices:[gu[0],gu[2]]}),z('初傳囚死',dormant(BE[f]),seasonAt(BE[f],mo)),c('初乘玄武白虎',gen[0]===9||gen[0]===7,r.transmissions[0].general),c('占時克行年',p.annualIndex==null?null:ke(BE[B.indexOf(r.hourBranch)],BE[p.annualIndex]),{hour:r.hourBranch,participant:p},['占人行年'])]);
  one('龍戰',9,[c('卯酉日卯酉發用',(d===3||d===9)&&(f===3||f===9),{day:B[d],first:B[f]}),c('占人行年亦卯酉',p.annualIndex==null?null:p.annualIndex===3||p.annualIndex===9,p,['占人行年'])]);
  one('死奇',9,[c('辰發用臨日辰陰陽四課下神',f===4&&[res,up[0],d,up[2]].includes(earth(4)),{first:B[f],earth:B[earth(4)],courseLowers:[res,up[0],d,up[2]].map(function(b){return B[b];})})],{resolutions:{dayQi:B[riqi],xunQi:B[qi],present:t.includes(riqi)||t.includes(qi)}});
  var disaster=[{name:'喪車',branch:mp==null?null:mod(7-3*mp,12)},{name:'遊魂',branch:mp==null?null:mod(11+mp,12)},{name:'伏殃',branch:mp==null?null:mod(9-3*mp,12)},{name:'病符',branch:yr==null?null:mod(yr-1,12)},{name:'喪門',branch:yr==null?null:mod(yr+2,12)},{name:'弔客',branch:yr==null?null:mod(yr-2,12)},{name:'歲虎',branch:yr==null?null:mod(yr-4,12)},{name:'日墓',branch:MUB[de]},{name:'沖墓',branch:mod(MUB[de]+6,12)}];
  one('災厄',9,[c('課經明列災厄煞發用',any(disaster.map(function(x){return x.branch==null?null:x.branch===f;})),disaster.map(function(x){return {name:x.name,branch:x.branch==null?null:B[x.branch],matched:x.branch==null?null:x.branch===f};}),['太歲與節氣月建'])],{historicalTerm:'神煞只作規則標記，不預報疾病、災難或死亡'});
  match('殃咎',10,[v('順遞克',[c('初克中、中克末、末克日',ke(BE[f],BE[mid])&&ke(BE[mid],BE[last])&&ke(BE[last],de),t.map(function(b){return E[BE[b]];}).concat(E[de]))]),v('逆遞克',[c('末克中、中克初、初克日',ke(BE[last],BE[mid])&&ke(BE[mid],BE[f])&&ke(BE[f],de),[last,mid,f].map(function(b){return E[BE[b]];}).concat(E[de]))]),v('三傳內外戰',[c('三傳俱神克將或俱將克神',t.every(function(b,i){return ke(BE[b],JG[gen[i]]);})||t.every(function(b,i){return ke(JG[gen[i]],BE[b]);}),r.transmissions.map(function(x,i){return {branch:x.branch,element:x.element,general:x.general,generalElement:E[JG[gen[i]]]};}))]),v('日辰俱乘墓',[c('干上日墓、支上支墓',up[0]===MUB[de]&&up[2]===MUB[db],{uppers:up.map(function(b){return B[b];}),tombs:[B[MUB[de]],B[MUB[db]]]})]),v('日辰俱坐墓',[c('天盤日寄宮及日支坐各自墓',earth(res)===MUB[de]&&earth(d)===MUB[db],{residenceEarth:B[earth(res)],branchEarth:B[earth(d)]})]),v('初傳夾克',[c('初傳受地盤與天將同克',ke(BE[earth(f)],BE[f])&&ke(JG[gen[0]],BE[f]),r.transmissions[0])])]);
  var uglyDays=['戊子','戊午','壬子','壬午','乙卯','乙酉','己卯','己酉','辛卯','辛酉'];
  match('九丑',10,[v('課經正文',[c('九丑干日',uglyDays.includes(r.day.ganzhi),r.day.ganzhi),c('丑臨四仲發用、占時亦四仲',f===1&&ZHONG.includes(earth(1))&&ZHONG.includes(B.indexOf(r.hourBranch)),{first:B[f],earth:B[earth(1)],hour:r.hourBranch})]),v('訂訛丑臨日支',[c('九丑干日',uglyDays.includes(r.day.ganzhi),r.day.ganzhi),c('丑臨日支',earth(1)===d,{uglyEarth:B[earth(1)],dayBranch:B[d]})])]);
  match('鬼墓',10,[v('日鬼',[c('三傳見同陰陽官鬼',t.some(function(b){return ke(BE[b],de)&&b%2===g%2;}),t.map(function(b){return {branch:B[b],element:E[BE[b]],samePolarity:b%2===g%2};}))]),v('日辰墓',[c('三傳有日干或日支之墓',t.includes(MUB[de])||t.includes(MUB[db]),{transmissions:t.map(function(b){return B[b];}),dayTomb:B[MUB[de]],branchTomb:B[MUB[db]]})])]);
  one('勵德',10,[c('貴人臨卯酉',earth(B.indexOf(r.noble.branch))===3||earth(B.indexOf(r.noble.branch))===9,r.noble)],{dayBranchYinGenerals:[co[1].general,co[3].general],dayBranchYangGenerals:[co[0].general,co[2].general]});
  match('盤珠',10,[v('天心',[c('歲月日時俱在四課上神',all([yr==null?null:up.includes(yr),mo==null?null:up.includes(mo),up.includes(d),up.includes(B.indexOf(r.hourBranch))]),{courseUppers:up.map(function(b){return B[b];}),year:yr==null?null:B[yr],month:mo==null?null:B[mo],day:B[d],hour:r.hourBranch},['太歲與月建'])]),v('回還',[c('三傳不出四課上神',t.every(function(b){return up.includes(b);}),{courseUppers:up.map(function(b){return B[b];}),transmissions:t.map(function(b){return B[b];})})])]);
  match('全局',10,[v('三合局',[c('三傳完整三合',fullTri(t),t.map(function(b){return B[b];}))]),v('稼穡局',[c('三傳三個不同季土',new Set(t).size===3&&t.every(function(b){return JIQU.includes(b);}),t.map(function(b){return B[b];}))])]);
  one('元胎',10,[c('三傳皆四孟',t.every(function(b){return MENG.includes(b);}),t.map(function(b){return B[b];}))],{subtype:r.rotation===3?'病胎':r.rotation===9?'生胎':r.rotation===6?'絕胎':r.rotation===0?'伏吟孟神':'四孟傳',historicalTerm:'不據課名預報妊娠或健康'});
  match('連珠',10,[v('進連茹',[c('三傳逐支進一',mid===mod(f+1,12)&&last===mod(mid+1,12),t.map(function(b){return B[b];}))]),v('退連茹',[c('三傳逐支退一',mid===mod(f-1,12)&&last===mod(mid-1,12),t.map(function(b){return B[b];}))])]);
  var fw=mid===mod(f+2,12)&&last===mod(mid+2,12),bw=mid===mod(f-2,12)&&last===mod(mid-2,12);
  match('間傳',10,[v('進間傳',[c('三傳逐支進二',fw,t.map(function(b){return B[b];}))]),v('退間傳',[c('三傳逐支退二',bw,t.map(function(b){return B[b];}))])],{subtype:fw?FORWARD[f]:bw?BACKWARD[f]:null,allTwentyFour:FORWARD.map(function(n,b){return {name:n,direction:'進',transmissions:[b,mod(b+2,12),mod(b+4,12)].map(function(x){return B[x];})};}).concat(BACKWARD.map(function(n,b){return {name:n,direction:'退',transmissions:[b,mod(b-2,12),mod(b-4,12)].map(function(x){return B[x];})};}))});
  var polar=up.concat(t),allYang=polar.every(function(b){return b%2===0;}),allYin=polar.every(function(b){return b%2===1;});
  match('六純',10,[v('六陽',[c('四課上神及三傳俱陽',allYang,polar.map(function(b){return B[b];}))]),v('六陰',[c('四課上神及三傳俱陰',allYin,polar.map(function(b){return B[b];}))])]);
  var mixed={2:['木中火長生'],4:['水土墓、餘木'],5:['火中金長生'],8:['金中水土長生'],7:['木墓、餘火'],10:['火墓、餘金'],11:['水中木長生'],1:['金墓、餘水']};
  one('雜狀物類',10,[c('取實際初傳五行純雜與六親',true,{first:B[f],element:E[BE[f]],pure:ZHONG.includes(f),mixed:mixed[f]||[],kinship:r.transmissions[0].kinship,polarity:f%2===0?'陽':'陰',earthPolarity:earth(f)%2===0?'陽':'陰',samePolarity:f%2===earth(f)%2,state:seasonAt(BE[f],mo),general:r.transmissions[0].general,beginningEnd:[r.transmissions[0],r.transmissions[2]]})],{sourceSections:['雜狀課','物類課'],grouping:'原典兩節合為一個64課族；無祿絕嗣同族分判，所有原典節名均保留',symbolic:'物類六親是五行相對關係，不據此指認真實人物或物件'});
  if(checks.length!==64)throw new Error('六壬課族數目不符，拒絕輸出不完整規則表。');
  return {schema:'jy.liuren-classes/1',version:VERSION,profile:'六壬大全課經正文為主，明列訂訛與其他署名變體',checks:checks,matched:checks.filter(function(x){return x.established===true;}),counts:{implemented:checks.length,established:checks.filter(function(x){return x.established===true;}).length,notEstablished:checks.filter(function(x){return x.established===false;}).length,insufficientData:checks.filter(function(x){return x.established===null;}).length},missing:Array.from(new Set(checks.filter(function(x){return x.established===null;}).flatMap(function(x){return x.missing;}))),participants:participants,calendar:context,auxiliary:{dayDe:B[dayDe],branchDe:B[zhiDe],tianDe:TD,yueDe:MD==null?null:G[MD],xunQi:B[qi],dayQi:B[riqi],branchYi:B[zhiyi],tianMa:tm==null?null:B[tm],lunarMansion:mansion,disasterStars:disaster.map(function(x){return {name:x.name,branch:x.branch==null?null:B[x.branch]};})},policy:{month:'神煞月序採節氣月建；旺相休囚死依本次seasonPolicy與實算seasonElementIndex，缺時仍可選整月五行。本命五行採本命支，另派納音不混入。',annual:'男一歲丙寅順行、女一歲壬申逆行，虛歲使用者明示；可直接覆核行年干支。',goodGenerals:'貴人、六合、青龍、太常、太陰、天后；其他為本版凶將類。',dayStrength:'亨通帝旺及天獄長生依五行，不把陰干逆長生表混入。',logic:'未提供年月曆法、年命及第二人資料時用三值判定；有已知成立的變體即可成立，否則不把未知當不成立。',coverage:'64課族成立條件、明列變體與盤面證據；不宣稱涵蓋各卷占類口訣的所有應期敘述或一切異派。',predictionValidated:false},sourceAudit:[{topic:'課族數目',choice:'雜狀與物類合族，保留兩節；無祿絕嗣各自判向',reason:'不刪原典節名以湊64'},{topic:'無祿絕嗣',choice:'正文無祿上克下、絕嗣下賊上',variant:'訂訛兩名相反'},{topic:'月宿',choice:'二煩起宿歌十月心宿並重留六宿',variant:'前文十月尾宿；粗排月宿不等於天文實測'},{topic:'天寇',choice:'正文四離與訂訛分至日取離辰分列',variant:'不可混用日期及昨日支'},{topic:'涉害取法與刑傷算例',choice:'本版庚午日寅時子將依歷歸本家深度取寅子戌，刑傷由申刑寅成立',variant:'課經刑傷例取午支自刑；不改三傳配合算例；其他取法須另選版本'}, {topic:'繁昌',choice:'本命旺相與兩行年干支合採書中德孕算例；旺孕格另列',variant:'發用條件在觀月經、曾門算例不是必要條件'}]};
 }
 root.JYLiurenClasses={version:VERSION,compute:compute,annual:annual,lunarMansion:lunarMansion,seasonal:seasonal,all:all,any:any};
 if(typeof module!=='undefined'&&module.exports)module.exports=root.JYLiurenClasses;
})(typeof window!=='undefined'?window:globalThis);
