/* Human-readable calculation output. No chart mutation, clipping or file requirement. */
(function(root){'use strict';
 const A=x=>Array.isArray(x)?x:[],keys=['Sun','Moon','Mercury','Venus','Mars','Jupiter','Saturn','Rahu','Ketu'],names=['日','月','水','金','火','木','土','羅','計'],signs=['牡羊','金牛','雙子','巨蟹','獅子','處女','天秤','天蠍','射手','摩羯','水瓶','雙魚'];
 const zh=k=>names[keys.indexOf(k)]||k,n=x=>typeof x==='number'&&Number.isFinite(x)?Math.round(x*10000)/10000:x;
 const meta=new Set(['source','sources','sourceAudit','sourceTextSHA256','sourceSha256','retrieved','license','version','schema','model','use','policy','scope','disclaimer','note','notes','encoding','strengthPolicy','referenceOrder','method','profile','basis','diagnostic','evidence']);
 const labels={status:'狀態',complete:'完整',missing:'缺',unknownTime:'時辰未知',conditions:'條件',checks:'核對',name:'名',value:'值',passed:'成立',established:'成立',selected:'採用',needsJudgment:'待判',assessment:'裁決',qualitativeRequirements:'質性待判',observablePremises:'字面前提',fullRuleStatus:'全條狀態',role:'角色',branch:'支',stem:'干',kinship:'六親',house:'宮',planet:'星',from:'從',to:'到',direction:'方向',reason:'依據',strength:'強度',phase:'入出相',angle:'角',orb:'距',start:'始',end:'終',startDate:'始日',endDateExclusive:'止日',endExclusive:'止',utc:'UTC',year:'年',month:'月',lord:'主',sign:'座',signName:'座名',degree:'度',longitude:'黃經',retrograde:'逆',tied:'等值',rule:'規則',selection:'取用',premises:'前提',summary:'作用',support:'支持',caution:'反證',label:'項',window:'時窗',interval:'區間',changes:'變動',obstacles:'阻',conclusion:'結論',quality:'品質',position:'爻位',element:'行',relative:'六親',general:'將',empty:'空',hiddenStem:'遁干',earth:'地',sky:'天',limit:'界',candidates:'候選',applicability:'適用',matched:'成立'};
 function text(v){if(v==null)return '未定';if(v===true)return '是';if(v===false)return '否';if(typeof v==='number')return String(n(v));if(typeof v!=='object')return String(v);if(Array.isArray(v))return v.map(text).join(',');return Object.entries(v).filter(([k,z])=>z!==undefined&&!meta.has(k)).map(([k,z])=>(labels[k]||k)+'='+text(z)).join(';');}
 const pick=(v,ks)=>Object.fromEntries(ks.filter(k=>v&&v[k]!==undefined).map(k=>[k,v[k]]));
 const stamp=v=>{if(v==null)return '未定';const d=new Date(v);return Number.isFinite(+d)?d.toISOString().replace('.000Z','Z'):String(v);};
 const interval=p=>p?stamp(p.start)+'→'+stamp(p.endExclusive??p.end):'未定';
 const flags=o=>o?Object.entries(o).filter(([,v])=>v===true).map(([k])=>labels[k]||k).join(','):'';
 function planet(k,p){return zh(k)+':'+(p.signName||signs[p.sign]||'?')+n(p.degree??((p.longitude??0)%30))+'°/宮'+(p.house??'?')+(p.retrograde?'逆':'')+(p.dignity?'('+text(p.dignity)+')':'');}
 function conditions(rows){return A(rows).map(p=>typeof p==='object'?(p.condition||p.name||p.id||p.label||'條件')+'='+text(pick(p,['value','status','passed','satisfied','needsJudgment','planet','house','dignity','sunSeparation'])):text(p)).join(',');}
 function rules(rows){return A(rows).map(p=>(p.name||p.id||p.label)+':'+text(p.status??p.assessment??p.value??p.established??'未定')+(p.rule?'('+p.rule+')':'')+((p.conditions||p.checks)?'['+conditions(p.conditions||p.checks)+']':'')+(p.needsJudgment?.length?'待判='+text(p.needsJudgment):'')).join('\n');}
 function checkTable(rows){const groups=new Map(),formed=[];for(const p of A(rows)){const state=text(p.status??p.established??'未定');if(!groups.has(state))groups.set(state,[]);groups.get(state).push(p.name||p.id);if(p.established===true||['structural','established','conditional'].includes(p.status))formed.push(p);}return Array.from(groups,([k,v])=>k+':'+v.join(',')).join('\n')+'\n成立項前提='+rules(formed);}
 const aspects=rows=>A(rows).map(p=>zh(p.a||p.from)+'→'+zh(p.b||p.to)+':'+(p.name||p.angle||p.house||'')+' '+n(p.orb??p.strength??p.virupas??0)+(p.phase||'')+(p.outOfSign?'跨座':'')+(p.utc?'@'+p.utc:'')).join(';');
 function dasha(d,label,detail=true){if(!d)return '未定';const lord=p=>typeof p.lord==='number'?signs[p.lord]:zh(p.lord),period=p=>p&&Object.keys(p).length?lord(p)+' '+interval(p):'未定',current=d.current?['maha','antar','pratyantar'].map(k=>period(d.current[k])).join('/'):'未定';return (d.system||label||'運期')+':'+(d.status||'calculated')+';適用='+text(d.applicability)+';當期='+current+';'+(detail?A(d.periods).map(p=>period(p)+'('+A(p.children).map(period).join(',')+')').join(';'):'')+(detail&&d.current?.pratyantars?.length?';當期三級='+d.current.pratyantars.map(period).join(','):'');}
 const sancai=g=>g?g.configuration+':'+A(g.versions).map(v=>v.profile+'='+v.level).join(',')+';生克='+text(g.relations):'未定';
 const grids=g=>g?g.grids.map(z=>z.role+z.num+'('+z.formula+')原著='+text(pick(z.originalNumerology,['number','theme','tone','summary']))+'/通行='+text(pick(z.commonModernTable,['level','theme']))).join(';')+'\n三才='+sancai(g.sanCai)+';陰陽='+text(g.yinYang):'未定';
 function render(entries,data,methodInstructions,footer){
  const out=['【完整純文字分析提示詞】',JSON.stringify({schema:'jy.native-analysis/1',method:data.method}),'原問題：'+JSON.stringify(data.question),'使用繁體中文直接解盤：先回答原題，逐子題交代主判、作用如何傳到結果、最強支持與反證、成立条件、時間及行動。用完整盤面交叉核對，勿見單一吉凶即下結論。未知與未實作項保持未知；不得猜造生日、時辰、他人意願或事件保證。這則訊息已含閱讀資料，不需要上傳附件。數值顯示至小數4位，原始精度留在引擎。日期有Z為UTC；區間右端不含。日月水金火木土為七曜，羅計為交點。'];
  if(data.notes!==null)out.push('補充：'+JSON.stringify(data.notes));
  const add=(label,v)=>{if(v!==undefined&&v!==null&&v!=='')out.push('【'+label+'】\n'+(typeof v==='string'?v:text(v)));};
  for(const e of entries){const c=e.chart,a=e.analysis,kind=e.method,section=l=>data.sections.find(s=>s.label===(e.label?e.label+' · ':'')+l)?.data,tag=e.label||kind;add(tag+'讀法',methodInstructions[kind]);
   if(a.coverage.provisional){for(const s of data.sections.filter(s=>!e.label||s.label.startsWith(e.label+' · ')))if(!/摘要|查核/.test(s.label))add(s.label,s.data);}
   else if(kind==='bazi'){
    add('四柱',a.pillars.map(p=>p.label+':'+p.gan+p.zhi+'透'+p.god+'藏'+p.hidden.map(h=>h.stem+h.god+(h.qi==='本氣'?'主':'')).join(',')+'納音'+(p.nayin||'')+'長生'+(p.lifeStage||'')).join('\n'));
    add('曆法與起運',text(pick(c.calculationPolicy,['referenceInstant','dayBoundaryMode','yearBoundary','monthBoundary','timeBasis']))+'\n'+text(pick(c.qiyun,['startAgeText','startUtc','direction','referenceJie','referenceJieDate','precision']))+';司令='+text(pick(c.renyuan,['gan','daysInTerm','elapsedDaysAfterJie','nominalStartDay','nominalEndDay']))+';空亡='+text(c.kongwang));
    add('強弱與根氣',text(pick(c.strengthAssessment,['level','quantitativeLevel','integratedDirection','monthSupportClass','conflict','conflictReason','structuralTensions']))+';實據='+text(c.strengthAssessment?.evidence)+';通根='+text(c.tongGen));
    add('扶抑與制化',text(pick(c.fuyiAssessment,['map','items','mechanisms','conclusion']))+'\n'+text(pick(c,['branchInteractions','hiddenInteractions','huaQiAssessments','energyFlow','bearingCapacity'])));
    const cl=c.classicalAssessment;add('八格成敗救應',cl?('月令取格='+text(cl.monthSelection)+'\n'+cl.patterns.map(p=>p.name+(p.selected?'(採用)':'')+' '+['formation','failure','taboo','rescue'].map(k=>({formation:'成',failure:'敗',taboo:'忌',rescue:'救'}[k])+':'+rules(p[k]).replace(/\n/g,'／')).join(';')).join('\n')):null);
    add('外格核對',rules(c.specialRuleAssessment?.rules));const qt=c.seasonalAssessment?.classicalClauses;add('調候原文與實算前提',qt?A(qt.sourceParagraphs).map(p=>'P'+p.paragraph+':'+p.text).join('\n')+'\n'+A(qt.checks).map(p=>p.id+':'+p.clause+';'+p.observablePremises+';待判'+text(p.qualitativeRequirements)+';條件'+text(p.conditions)).join('\n'):c.seasonalAssessment);
    const y=section('大運與所問年度');add('大運',y?.decades.map(d=>d.gz+':'+d.ageStart+'–'+d.ageEnd+'歲 '+interval(d.window)+(d.isCurrent?'目前':'')).join('\n'));add('流年',y?.annualSegments.map(v=>v.year+' '+v.dayun+'/'+v.annual+' '+v.god+' '+interval(v.window)+' '+text(v.connections)+';調候='+text(v.seasonal)).join('\n'));add('年度缺項',y?.missingYears);add('流月',A(c.liuYue).map(p=>p.monthName+p.gz+':'+p.label+(p.isChong?'沖':'')+(p.isHe?'合':'')).join(';'));
   }else if(kind==='ziwei'){
    add('定盤政策',text(c.birthInput)+';農曆='+text(c.birthLunar)+';'+text(pick(c.calculationPolicy,['dayBoundaryMode','leapMonthPolicy','sihuaProfile','flowStarPolicy','referenceLunarYear']))+';局='+text(c.wuxingJu)+';命主='+c.mingZhu+';身主='+c.shenZhu);
    add('十二宮(星曜、亮度、化)',c.palaces.map(p=>p.name+p.gan+p.branch+(p.isShen?'身':'')+':'+p.stars.map(s=>s.name+(root.getStarBright?root.getStarBright(s.name,'子丑寅卯辰巳午未申酉戌亥'.indexOf(p.branch))?.label||'':'')+(s.hua||'')).join(',')).join('\n'));
    add('生年與自化',text(c.sihua)+'\n'+text(c.selfHua));add('宫干飛化',A(c.northern?.flights).map(f=>f.fromBranch+f.gan+'→'+f.toBranch+f.star+f.kind+(f.self?'自化':'')+(f.centripetal?'向心':'')).join('\n'));add('轉象',c.northern?.transitions);
    add('格局',rules(c.patternAssessment?.patterns)+'\n'+rules(c.patternAssessment?.catalog));const l=section('運限疊宮');
    const layer=p=>p?((p.layer||'流年')+(p.month?(p.year||'')+'/'+p.month:p.year||p.ageStart+'–'+p.ageEnd)+(p.context?'('+text(p.context)+')':'')+' '+(p.gan||'')+(p.branch||'')+';四化='+A(p.hua).map(h=>h.star+h.hua+'→'+(h.palaceBranch||h.branch||h.palace)).join(',')+';宮職='+A(p.palaces).map(v=>(v.periodPalace||v.name)+v.branch).join(',')+';流曜='+A(p.palaces).flatMap(v=>A(v.flowStars).map(f=>(f.displayName||f.star)+v.branch)).join(',')):'';
    add('全部大限',l?.decades.map(layer).join('\n'));add('運限',l?[l.annual,...l.months,l.daily,l.hourly].map(layer).join('\n'):null);add('所問其他流年',A(section('明示年度流年')).map(layer).join('\n'));add('缺年度',section('流年輸出範圍')?.missingYears);
   }else if(kind==='vedic'){
    add('吠陀政策',text(c.input)+';'+text(pick(c.policy,['ayanamsa','ayanamsaDegrees','node','houses','strengthStatus']))+';上升='+text(c.lagna));add('D1九曜',Object.entries(c.planets).map(([k,p])=>planet(k,p)+'月宿='+text(p.nakshatra)+'燃燒='+text(p.solar)).join('\n'));add('D1十二宮與相位',text(c.houses)+'\n'+text(c.aspects));add('定位與掌宮',text(c.dispositors)+';關係='+text(pick(c.relationships,['natural','temporary','compound']))+';Karaka='+text(c.karakas));
    add('所有16分盤星位(依日月水金火木土羅計順序)',Object.values(c.vargas).map(v=>'D'+v.division+'('+v.purpose+')上升='+text(v.lagna)+';'+keys.map(k=>{const p=v.planets[k];return (p.signName||signs[p.sign])+(Number.isFinite(p.degree)?n(p.degree)+'°':'')+'/宮'+(p.house??'?')+(p.vargottama?'同位':'');}).join(',')).join('\n'));
    add('六力(位向時動自然照射)、門檻、Ishta/Kashta',A(c.strength?.planets).map(p=>zh(p.planet)+':'+['sthana','dig','kala','cheshta','naisargika','drik'].map(k=>k+'='+text(p[k]?.components||p[k]?.virupas)).join(';')+'總='+n(p.totalVirupas)+'/'+n(p.minimumVirupas)+';足='+p.meetsMinimum+';'+text(p.ishtaKashta)).join('\n'));
    add('12宮力與九曜宮界比例',A(c.bhavaStrength?.houses).map(h=>h.house+':主='+h.lord+';adhipathi='+n(h.adhipathi?.virupas??h.adhipathi)+';向='+n(h.dig?.virupas??h.dig)+';照='+n(h.drishti?.virupas)+';總='+n(h.totalVirupas)).join('\n')+'\n'+text(c.bhavaStrength?.residential));add('五支曆',c.panchanga);
    add('格局核對',checkTable(c.yogas)+'\n'+checkTable(c.specialRules?.checks)+'\n'+checkTable(c.advanced?.yogas?.checks)+'\n落陷取消='+A(c.advanced?.yogas?.neechabhanga).map(p=>zh(p.planet)+':落陷='+text(p.debilitated)+'主='+zh(p.debilitationLord)+'擢主='+zh(p.exaltationLord)+';'+conditions(p.conditions)+';取='+text(p.structuralCancellation)).join('\n'));
    const ds=section('所問運期與行運');
    add('Vimshottari全所問區間；其他17運法適用與當期(明示運名或全部運期才列全所問區間)',[dasha(ds?.vimshottari,'Vimshottari'),...Object.entries(ds?.additional||{}).map(([k,d])=>dasha(d,k,/(?:全部|所有).{0,6}(?:運期|運法|Dasha)|(?:運期|運法).{0,6}(?:全部|所有)/i.test(data.question)||data.question.toLowerCase().includes(k.toLowerCase())))].join('\n'));add('行運與月快照',text(ds?.transits)+'\n'+A(ds?.transitSnapshots).map(s=>s.utc+':'+Object.entries(s.planets||{}).map(([k,p])=>zh(k)+(p.signName||signs[p.sign]||'')+n(p.degree??p.longitude%30)+'°'+(p.retrograde?'逆':'')+'/月'+(p.fromMoon??'?')+'/升'+(p.fromLagna??'?')).join(',')).join('\n'));
    const av=section('八分法所有分盤');add('八分法(牡羊至雙魚12座；PAV八數依日月火水木金土升；bit0=牡羊)',Object.entries(av?.vargas||{}).map(([k,v])=>'D'+k+' SAV='+text(v.sav)+';BAV='+text(v.bav)+';PAV='+text(v.prastaraMasks)+';消減Trikona/Ekadhipatya/Soav與Pinda='+text(v.reductions)+';Pinda係數='+text(v.pindaFactors)).join('\n'));
    const ja=section('Jaimini與特殊點');add('Arudha、Argala与Narayana(D1所問區間，其他盤當期；點名Narayana才列所有所選盤區間)',Object.entries(ja?.vargas||{}).map(([k,v])=>'D'+k+' Arudha='+text(A(v.arudhas?.bhava).map(p=>p.name+'='+signs[p.sign]+'(主'+zh(p.lordSelection?.winner)+(p.exception?'例外':'')+')'))+';星影='+A(v.arudhas?.graha).map(z=>zh(z.planet)+'='+signs[z.sign]).join(',')+';Argala='+A(v.argala?.signs).map(s=>s.sign+':'+A(s.channels).map(z=>z.argalaHouse+'/'+z.obstructionHouse+':'+A(z.contributors).map(zh).join(',')+'|'+A(z.blockers).map(zh).join(',')+'='+z.countDecision+(z.vipareeta?'逆向':'')+(z.quarterCounterpairs?.length?'角度配對'+text(z.quarterCounterpairs):'')).join('/')).join(';')+';共主='+A(v.coLords).map(z=>signs[z.sign]+'='+text(z.selection||z)).join(',')+';'+dasha(v.narayana,'Narayana',Number(k)===1||/Narayana|所有運期|全部運期/i.test(data.question))).join('\n'));add('8Karaka與特殊點',text(ja?.eightKarakas)+'\n'+text(ja?.specialPoints));
   }else if(kind==='astro'){
    add('西洋政策',text(c.input)+';'+text(pick(c.policy,['houseSystem','zodiac','progressedAngles'])));add('全部星位',Object.entries(c.planets).map(([k,p])=>planet(k,p)+'速='+n(p.speed)).join('\n'));add('十二宮頭與四角',c.houses);add('相位與定位',aspects(c.aspects)+'\n'+text(c.dispositors));
    const ed=c.essentialDignities;add('尊貴與接納',A(ed?.planets).map(p=>zh(p.planet)+':持='+text(p.held)+';失勢='+p.detriment+'落陷='+p.fall+'游離='+text(p.peregrine)+';座擢三界面='+['signLord','exaltationLord','triplicityLord','termLord','faceLord'].map(k=>zh(p[k]||'無')).join('/')+';界='+text(p.termInterval)+'面='+text(p.faceInterval)).join('\n')+'\n'+A(ed?.dignityHosting).map(h=>zh(h.host)+'接納'+zh(h.guest)+'('+h.dignities.join(',')+')').join(';')+'\n'+text(ed?.mutualHosting?.map(p=>({a:p.a.host,b:p.b.host,aToB:p.b.dignities,bToA:p.a.dignities}))));add('格局与條件',text(c.patterns)+'\n'+text(c.chartShapes)+'\n'+text(c.specialConditions));
    const future=(p,label)=>{if(!p)return;add(label+'時刻與星位',p.utc+';'+text(pick(p,['referenceUTC','year','angleMethod','locationPolicy','purpose']))+'\n'+Object.entries(p.planets||{}).map(([k,v])=>planet(k,v)).join(';')+'\n宮頭='+text(p.houses?.cusps)+';四角='+text(p.houses?.angles));add(label+'相位及本命疊宮',aspects(p.aspects)+'\n角度='+aspects(p.angleAspects)+'\n盤內='+aspects(p.chartAspects)+'\n疊宮='+text(p.natalHouseOverlay||p.natalOverlay));};future(a.transits,'行運');future(a.progressions,'次限');future(a.returnAnalysis,'太陽回歸');
    if(c.horary){const h=c.horary;add('卜卦宮主與兩方',A(h.significators).map(p=>p.house+'宮='+zh(p.lord)).join(';')+';问事宮='+h.selectedHouse+';問方='+zh(h.querent?.lord)+';事方='+zh(h.quesited?.lord));add('卜卦光圈與相位',text(h.orbPolicy)+'\n'+aspects(h.traditionalAspects));add('傳光集光與六類受阻實算',text(h.translationChecks||h.translationCandidates)+'\n'+text(h.collectionChecks||h.collectionCandidates)+'\n'+text(h.denialChecks||h.perfectionAndInterference));add('月亮空亡各版',h.moon);add('完整卜卦星象時序',aspects(h.timeline?.events)+'\n换座='+text(h.timeline?.ingresses)+'\n駐留='+text(h.timeline?.stations));}if(c.relocated)future(c.relocated,'迁居同UTC');
   }else if(kind==='liuren'){
    add('日時、钟制与時令',text(pick(c,['time','day','monthGeneral','hourBranch','rotation','daytime','noble','xun','method']))+'\n'+text(c.clock)+'\n'+text(c.seasonal));add('天地盤',a.plate.map(p=>text(pick(p,['earth','sky','general','kinship','empty','hiddenStem']))).join('\n'));add('四課與三傳',a.courses.map(p=>text(p)).join('\n')+'\n'+a.transmissions.map(p=>text(p)).join('\n'));add('生克與取用',text(a.edges)+'\n'+text(a.ganZhi)+'\n'+text(c.timing?.selection));
    add('64課體三值核對',A(c.classAnalysis?.checks).map(p=>p.name+':'+p.status+(p.missing.length?'缺'+text(p.missing):'')).join(';'));add('神煞全部實際命中',A(c.shensha?.active).map(p=>p.name+'('+text(p.location)+')'+A(p.hits).map(h=>text(pick(h,['kind','role','branch','position','index']))).join('/')).join(';'));add('神煞缺項',c.shensha?.missing);
    const t=section('取用與候選日實算');add('實算应期時窗',text(t?.window)+';候選數='+t?.candidateCount+';逐日核對='+t?.inspectedDayCount);const g=t?.candidateGroups;if(g){add('候選區段表(毫秒偏移相加於該日00:00UTC)',g.timeOffsetsMs.map((v,i)=>'W'+i+'='+v.join(',')).join(';'));const why=[],whyIndex=new Map(),limits=[],limitIndex=new Map(),subjects=[],subjectIndex=new Map(),intern=(rows,map,v)=>{const k=JSON.stringify(v);if(!map.has(k)){map.set(k,rows.length);rows.push(v);}return map.get(k);};
      const cs=g.conditionDefinitions.map(d=>[intern(subjects,subjectIndex,pick(d,['target','role','branch'])),intern(why,whyIndex,d.why),...d.monthConstraints.map(z=>intern(limits,limitIndex,[z.monthBranch,z.monthlyBroken,z.season,z.dayEmpty,z.startOffsetMs,z.endOffsetMs]))]);
      add('候選取用表T',subjects.map((d,i)=>'T'+i+'='+text(d)).join(';'));add('候選觸發表R',why.map((d,i)=>'R'+i+'='+text(d)).join(';'));add('候選月令表M(月支/破/旺衰/日空/起止UTC毫秒偏移)',limits.map((d,i)=>'M'+i+'='+text(d)).join(';'));add('候選條件C(取用T/觸發R/每個月令M)',cs.map((v,i)=>'C'+i+'='+v.join('/')).join(';'));
      const months=new Map();for(const d of g.days){const month=d.date.slice(0,7);if(!months.has(month))months.set(month,[]);months.get(month).push(d.date.slice(8)+'/'+d.dayGanzhi+'/'+d.monthBranch+'/'+d.xunHead+'/W'+d.timeIndex+'/'+d.conditions.join(','));}add('全部候選日(按年月列：日/干支/月支/旬首/區段W/條件C索引)',Array.from(months,([m,rows])=>m+':'+rows.join(';')).join('\n'));}
   }else if(kind==='liuyao'||kind==='yijing'){
    add('起卦記錄',text(pick(c,['system','method','values','movingPositions','calendar','original','changed','hasChange'])));add('全部六爻(由初爻至上爻)',c.lines.map(p=>text(pick(p,['position','label','value','stem','branch','element','relative','role','spirit','states','moving','changed','transition','hidden']))).join('\n'));
    if(kind==='liuyao')add('取用、旺衰、動變及應期',c.interpretation);else add('朱子主讀與原典彖象文言',text(c.reading)+'\n'+text(c.originalText)+'\n'+text(c.changedText)+'\n'+text(c.expositions)+'\n'+text(c.complementaryViews));
   }else if(kind==='name'){
    add('比較範圍',text(pick(c,['surname','baseline','candidateNames','criteria','purpose'])));for(const p of A(c.names).length?c.names:[c]){add('姓名 '+p.name,A(p.characters).map(ch=>ch.char+':康熙'+ch.kangxi+'/現代'+ch.modern+'音'+text(ch.readings)+'義'+ch.meaning+'根'+text(ch.roots)).join(';')+'\n五格='+grids(p.fiveGrids)+'\n筆畫異表='+text(p.strokeSensitivity?.differences)+';現代筆畫='+grids(p.strokeSensitivity?.alternateFiveGrids)+'\n音義='+text(pick(p.phonetic,['status','resolution','toneSequence','writingStrokes','warnings','checks']))+';生肖='+text(p.zodiac)+'\n姓名卦='+text(p.nameGua)+'\n八字連結='+text(p.bazi));}
    add('所有比較對',A(c.comparison?.pairs).map(p=>p.baseline+'→'+p.candidate+';同名='+p.sameName+';五格差='+text(p.fiveGrids)+';三才='+text(pick(p.sanCai,['baseline','candidate','changed','same','relationshipChanges']))+';生肖='+text(p.zodiac)+';八字='+text(p.bazi)).join('\n'));
   }else if(kind==='compat'){
    const person=p=>text(pick(p,['name','gender','birthLine','trueSolarDateTime','pillars','dayMaster','strength','elementWeights','favorable','unfavorable','unknownTime','birthInput','birthLunar','palaces','sihua','selfHua','northern']));add('双方原局', 'A:'+person(c.personA)+'\nB:'+person(c.personB));add('雙向十神與跨柱生克',text(pick(c,['scenario','dayMasters','spousePalace','directionalTenGods','stemRelations','branchRelations','groupRelations','elementComplement','uncertainty','overlays','directions','projectionGroups','birthTimeAudit','timeline','unavailable'])));const luck=section('雙方及雙向原盤作用')?.luckSynchronization;add('所问雙方運期',luck?'A當期='+text(pick(luck.aCurrent,['gz','ageStart','ageEnd','window','god','zGod','notes']))+'\nB當期='+text(pick(luck.bCurrent,['gz','ageStart','ageEnd','window','god','zGod','notes']))+'\n'+A(luck.years).map(y=>y.year+' '+interval(y.window)+' A:'+A(y.a?.segments).map(v=>v.dayun+'/'+v.gz+' '+v.god+' '+interval(v.window)+';沖'+text(v.clash)+';作用'+text(v.events)+';條件'+text(v.notes)).join(';')+' B:'+A(y.b?.segments).map(v=>v.dayun+'/'+v.gz+' '+v.god+' '+interval(v.window)+';沖'+text(v.clash)+';作用'+text(v.events)+';條件'+text(v.notes)).join(';')).join('\n'):null);
   }
   else if(kind==='personality'){add('五軸人格實算与界線',section('五軸實算與模型界線'));}
   else if(kind==='meihua'){add('本互變、體用與原體階段',text(c)+'\n'+a.items.map(p=>p.label+':'+text(p.evidence)).join('\n'));}
   else{add('本次所有牌籤與程序',a.methodData);if(kind==='oracle'){const r=root.JYOracleRegister?.get(c.n??c.number);if(r)add('原廟分類索引(特徵非原文)',r.categories||r.classifications);}add('程序狀態',pick(c,['methodPlan','sourceProfile','spread','spreadType','drawProcedure','status','gate']));}
   add(tag+'逐項作用与反證',a.items.map(p=>p.label+':'+p.summary+(p.support?.length?' 支持='+p.support.join(','):'')+(p.caution?.length?' 反證='+p.caution.join(','):'')).join('\n'));
   add(tag+'缺項',a.unavailable);add(tag+'採用來源',a.sources.map(s=>s.id+'='+s.url).join(';'));
  }
  out.push('依上述盤面完成原題全部子題；不要把未知條件當確定、不只羅列術語。給可核對的支持與反證、時間及行動，並以本題需要決定篇幅；最後可給象徵性配戴提醒，不宣稱療效或保證改運。',footer||'');
  // Repeated prose is defined once; references remain legible and reversible.
  let body=out.join('\n\n');const definitions=[],counts=new Map();for(const line of body.split('\n'))if(line.length>100)counts.set(line,(counts.get(line)||0)+1);for(const [line,count]of counts)if(count>1){const id='同項'+(definitions.length+1);body=body.split(line).join('〔'+id+'〕');definitions.push(id+'='+line);}return (definitions.length?body+'\n【共用完整內容】\n'+definitions.join('\n'):body)+'\n【資料結束】';
 }
 root.JYPromptBrief=Object.freeze({version:'20261003brief6',render,text});
})(typeof window==='undefined'?globalThis:window);
