/* A standalone Indian astrology ceremony. Not the shared character/ritual player. */
(function(root){
  'use strict';
  let active=null,loading=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function loadScene(){if(root.JYVedicScene)return Promise.resolve();if(loading)return loading;
    loading=new Promise((resolve,reject)=>{let timer=setTimeout(()=>reject(Error('scene timeout')),7000);const s=document.createElement('script');s.src='JS/vedic-scene.js?v=20260914sanctum1';s.onload=()=>{clearTimeout(timer);resolve();};s.onerror=()=>{clearTimeout(timer);loading=null;reject(Error('scene unavailable'));};document.head.appendChild(s);}).catch(e=>{loading=null;throw e;});return loading;}
  function fallback(chart){const C=root.JYVedic,rows=[['日','月','火'],['水','木','金'],['土','羅','計']];return '<div class="vdr-fallback" aria-hidden="true"><img src="assets/ui/vedic-jaali.svg" alt=""><div class="vdr-fallback-core"><span>NAVAGRAHA</span><b>'+esc(chart.lagna?chart.lagna.signName:'月亮')+'</b><small>'+esc(chart.planets.Moon.nakshatra.name)+'</small><div>'+C.KEYS.map(k=>'<i>'+esc(C.zh(k))+'</i>').join('')+'</div></div></div>';}
  function play(chart,options={}){
    if(active)active.cancel();let done,scene=null,frame=0,dead=false,start=performance.now(),elapsed=0,lastTime=start,stage=-1,still=!!options.reduced;
    const D=document,entry=D.activeElement,modal=D.createElement('dialog'),C=root.JYVedic,n=chart.planets.Moon.nakshatra;modal.id='vd-ceremony';modal.className='vd-modal vdr-modal';modal.dataset.motion=still?'still':'full';modal.setAttribute('aria-label','印度占星專屬星盤演出');
    modal.innerHTML='<div class="vdr-room" aria-hidden="true"></div><header class="vdr-header"><span class="vdr-mark">✧ <small>JYOTISHA</small></span><button type="button" data-vdr="cancel" class="vd-quiet">返回資料</button></header><div class="vdr-copy"><span class="vd-kicker">NAVAGRAHA · 九曜入盤</span><h2 id="vdr-title">定位出生的天空</h2><p id="vdr-caption">'+esc(chart.input.civil?.date||chart.input.utc.slice(0,10))+' · '+esc(chart.input.location||'自訂出生地')+'</p></div><div class="vdr-stage">'+fallback(chart)+'<div id="vdr-canvas" class="vdr-canvas"></div><span class="vdr-orbit-label">27 NAKSHATRA · 12 RASHI · 9 GRAHA</span></div><div class="vdr-bottom"><div class="vdr-phases" aria-label="演出階段"><span>01 月宿</span><span>02 九曜</span><span>03 命盤</span></div><div class="vdr-progress" aria-hidden="true"><i></i></div><p id="vdr-fact" aria-live="polite"></p><button type="button" data-vdr="open" class="vd-primary" '+(still?'':'disabled')+'>展開我的印度命盤 →</button><button type="button" data-vdr="skip" class="vdr-skip">略過演出</button></div>';
    D.body.appendChild(modal);try{modal.showModal();}catch(_){modal.setAttribute('open','');modal.classList.add('vd-modal-fallback');}
    const finished=new Promise(r=>done=r);const end=outcome=>{if(dead)return;dead=true;cancelAnimationFrame(frame);scene?.dispose();modal.close?.();modal.remove();D.removeEventListener('visibilitychange',visibility);if(entry?.isConnected&&!entry.disabled)entry.focus({preventScroll:true});active=null;done(outcome);};
    active={finished,cancel:()=>end(false)};
    function setStage(p){const index=still||p>=.94?3:p<.3?0:p<.62?1:2;if(index===stage)return;stage=index;modal.dataset.stage=String(index);const names=['定位出生的天空','九曜，循星位入盤','十二宮，展開生命脈絡','你的命盤已定位'];const captions=[n.name+' · 第 '+n.pada+' 足','依本命恆星黃道位置，逐一安置九曜。',chart.lagna?'上升 '+chart.lagna.signName+' · 北印度式命盤':'出生時間未知 · 保留可核對的星座位置','從本命、分盤與運期，理解當下。'];modal.querySelector('#vdr-title').textContent=names[index];modal.querySelector('#vdr-caption').textContent=captions[index];modal.querySelector('#vdr-fact').textContent=index===0?'本命月宿主：'+C.zh(n.lord):index===1?'月亮：'+chart.planets.Moon.signName+' · 九曜位置來自本次排盤':index===2?'同一份出生資料，將接續展開十六分盤與運期。':'星位與運期已保留，準備好就進入命盤。';modal.querySelectorAll('.vdr-phases span').forEach((x,i)=>x.dataset.active=String(i===Math.min(index,2)));if(index===3)modal.querySelector('[data-vdr="open"]').disabled=false;}
    function draw(now){if(dead)return;const dt=Math.max(0,now-lastTime);lastTime=now;if(!D.hidden)elapsed+=dt;const p=still?1:Math.min(1,elapsed/10200);setStage(p);scene?.render(p);modal.querySelector('.vdr-progress i').style.transform='scaleX('+p+')';if(p<1&&!D.hidden)frame=requestAnimationFrame(draw);}
    function visibility(){lastTime=performance.now();cancelAnimationFrame(frame);if(!D.hidden&&!dead)frame=requestAnimationFrame(draw);}
    D.addEventListener('visibilitychange',visibility);modal.addEventListener('cancel',e=>{e.preventDefault();end(false);});modal.addEventListener('click',e=>{const a=e.target.closest('[data-vdr]')?.dataset.vdr;if(a==='cancel')end(false);if(a==='skip'||a==='open')end(true);});
    modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();end(false);}if(e.key==='Tab'){const a=[...modal.querySelectorAll('button')].filter(b=>!b.disabled);if(e.shiftKey&&D.activeElement===a[0]){e.preventDefault();a.at(-1).focus();}else if(!e.shiftKey&&D.activeElement===a.at(-1)){e.preventDefault();a[0].focus();}}});
    const host=modal.querySelector('#vdr-canvas');host.addEventListener('vedic-scene-lost',()=>{scene?.dispose();scene=null;modal.dataset.renderer='fallback';});
    Promise.all([loadScene(),document.fonts?.ready||Promise.resolve()]).then(()=>{if(dead)return;try{scene=root.JYVedicScene.create(host,chart);scene.render(still?1:Math.min(1,elapsed/10200));modal.dataset.renderer='webgl';}catch(_){modal.dataset.renderer='fallback';}}).catch(()=>{if(!dead)modal.dataset.renderer='fallback';});
    frame=requestAnimationFrame(draw);modal.querySelector('[data-vdr="cancel"]').focus({preventScroll:true});return active;
  }
  root.JYVedicRitual=Object.freeze({play,preload:loadScene,isActive:()=>!!active,cancel:()=>active?.cancel()});
})(window);
