/* Cancellable Western-only choreography. No random chart recomputation. */
(function(root){
 'use strict';let active=null,loading=null;const D=root.document,DURATION=12500;
 function load(){if(root.JYWesternScene)return Promise.resolve();if(loading)return loading;loading=new Promise((resolve,reject)=>{const s=D.createElement('script');s.src='JS/western-scene.js?v=20260914western1';s.onload=resolve;s.onerror=()=>{loading=null;reject(Error('3D 場景無法載入'));};D.head.appendChild(s);});return loading;}
 function play(chart,{reduced=false}={}){
  active?.cancel();const previous=D.activeElement,dialog=D.createElement('dialog');dialog.id='wx-ceremony';dialog.className='wx-ceremony';dialog.dataset.renderer='loading';dialog.setAttribute('aria-labelledby','wx-ceremony-title');
  dialog.innerHTML='<div class="wx-ceremony-bg"></div><div class="wx-ceremony-stage"></div><div class="wx-ceremony-fallback"><div>'+root.JYWesternChart.wheel(chart,{selected:null,interactive:false,id:'wx-fallback'})+'</div></div><header class="wx-ceremony-top"><span>✥ THE CELESTIAL ATLAS</span><button type="button" data-wxr="cancel">返回資料</button></header><div class="wx-ceremony-heading"><small id="wx-ceremony-label">I · THE OBSERVATORY</small><h2 id="wx-ceremony-title">星穹，為你轉動。</h2><p id="wx-ceremony-desc">黃道儀升起，循著出生時刻定位。</p></div><footer class="wx-ceremony-bottom"><div class="wx-ceremony-chapters"><span class="on">01 黃道儀升起</span><span>02 星辰歸位</span><span>03 星盤展開</span></div><button type="button" class="wx-primary" data-wxr="open" disabled>展開我的西洋命盤 <span>→</span></button><button type="button" class="wx-ceremony-skip" data-wxr="skip">略過演出</button></footer>';
  D.body.appendChild(dialog);dialog.showModal();let resolve,done=false,scene=null,frame=0,start=null,last=0,ready=false,phase=-1;const finished=new Promise(r=>resolve=r);
  function end(result){if(done)return;done=true;cancelAnimationFrame(frame);scene?.dispose();dialog.close();dialog.remove();previous?.focus?.({preventScroll:true});resolve(result);if(active===api)active=null;}
  function labels(p){const i=p<.32?0:p<.79?1:2;if(i===phase)return;phase=i;const all=[['I · THE OBSERVATORY','星穹，為你轉動。','黃道儀升起，循著出生時刻定位。'],['II · THE CELESTIAL MECHANISM','每顆星，都有它的位置。','機械星門展開，星位與宮位逐一相遇。'],['III · YOUR NATAL ATLAS','你的星圖，已然成形。','輕拖星儀感受立體視角，準備好就進入命盤。']][i];D.getElementById('wx-ceremony-label').textContent=all[0];D.getElementById('wx-ceremony-title').textContent=all[1];D.getElementById('wx-ceremony-desc').textContent=all[2];dialog.querySelectorAll('.wx-ceremony-chapters span').forEach((s,n)=>s.classList.toggle('on',n===i));}
  function tick(t){if(done)return;if(start===null)start=t;const p=reduced?1:Math.min(1,(t-start)/DURATION);labels(p);if(p===1&&!ready){ready=true;dialog.querySelector('[data-wxr="open"]').disabled=false;}if(t-last>=32||reduced){scene?.update(p,(t-start)/1000);last=t;}if(!reduced)frame=requestAnimationFrame(tick);}
  dialog.addEventListener('cancel',e=>{e.preventDefault();end('cancelled');});dialog.addEventListener('click',e=>{const a=e.target.closest('[data-wxr]')?.dataset.wxr;if(a==='cancel')end('cancelled');if(a==='skip'||a==='open'&&ready)end('finished');});
  const api={finished,cancel:()=>end('cancelled'),getSceneState:()=>scene?.state()||{renderer:dialog.dataset.renderer,progress:ready?1:0}};active=api;dialog.querySelector('[data-wxr="cancel"]').focus();
  (async()=>{try{if(reduced)throw Error('reduced motion');await load();if(done)return;const made=await root.JYWesternScene.create(dialog.querySelector('.wx-ceremony-stage'),chart);if(done){made.dispose();return;}scene=made;dialog.dataset.renderer='webgl';dialog.querySelector('canvas').addEventListener('webglcontextlost',event=>{if(done)return;event.preventDefault();const lost=scene;scene=null;lost?.dispose();dialog.dataset.renderer='fallback';reduced=true;});}catch(_){if(done)return;dialog.dataset.renderer='fallback';reduced=true;}frame=requestAnimationFrame(tick);})();
  return api;
 }
 root.JYWesternRitual=Object.freeze({play,isActive:()=>!!active,getSceneState:()=>active?.getSceneState()||null});
})(globalThis);
