/* PVR27/28/30 selected solar-year arithmetic. Sidereal solar motion, birthplace
 * coordinates, Harsha components, 36 sahams and three annual dasha models. */
(function(root){'use strict';
 const yearlyClocks=new WeakMap();
 const DAY=86400000,K=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn'],O=['Sun','Moon','Mars','Rahu','Jupiter','Saturn','Mercury','Ketu','Venus'],Y=[6,10,7,18,16,19,17,7,20],mod=(n,m)=>(n%m+m)%m,source='https://www.vedicastrologer.org/articles/vedic_astro_textbook.pdf';
 function solar(chart,t){const A=root.Astronomy,E=root.JYVedic,x=A.MakeTime(new Date(t)),tilt=A.e_tilt(x);return E.norm(A.Ecliptic(A.GeoVector('Sun',x,true)).elon-E.meanAyanamsa(x.ut+2451545,chart.input.ayanamsa)-tilt.dpsi/3600);}
 function crossing(chart,target,guess){const E=root.JYVedic;let a=guess-6*DAY,b=guess+6*DAY,fa=E.diff(solar(chart,a),target),fb=E.diff(solar(chart,b),target);if(!(fa<=0&&fb>=0))throw Error('太陽回歸未被12日根區間夾住');let t=guess;
  for(let i=0;i<12;i++){const f=E.diff(solar(chart,t),target);if(Math.abs(f)<1e-7)break;if(f<0)a=t;else b=t;const rate=E.diff(solar(chart,t+DAY/48),solar(chart,t-DAY/48))/(DAY/24),step=t-f/rate;t=Number.isFinite(step)&&step>a&&step<b?step:(a+b)/2;if(b-a<250){t=(a+b)/2;break;}}
  let f=E.diff(solar(chart,t),target);if(Math.abs(f)>1e-6){for(let i=0;i<32&&b-a>250;i++){t=(a+b)/2;f=E.diff(solar(chart,t),target);if(f<0)a=t;else b=t;}t=(a+b)/2;}
  const utc=Math.round(t);return {utc:new Date(utc).toISOString(),longitude:solar(chart,utc),target:E.norm(target),errorDegrees:Math.abs(E.diff(solar(chart,utc),target))};}
 function sahams(c){
  const E=root.JYVedic,p=c.planets,L=c.lagna.longitude,day=c.strength?.clock?.segment?.daytime;
  if(typeof day!=='boolean')return {status:'unknown-day-night',points:[],missing:['原地日夜判定']};
  const v={...Object.fromEntries(K.map(k=>[k,p[k].longitude])),Lagna:L,lagnaLord:p[E.LORDS[c.lagna.sign]].longitude};
  const house=n=>E.norm(L+(n-1)*30),lord=n=>p[E.LORDS[mod(c.lagna.sign+n-1,12)]].longitude,points=[];
  function add(name,A,B,C=L,invariant=false){if(!day&&!invariant)[A,B]=[B,A];const arc=E.norm(A-B),between=E.norm(C-B)<=arc,uncorrected=E.norm(A-B+C),longitude=E.norm(uncorrected+(between?0:30));v[name]=longitude;points.push({name,...E.placement(longitude),lord:E.LORDS[Math.floor(longitude/30)],operands:{A,B,C},day,nightReversed:!day&&!invariant,COnArcFromBToA:between,correction:between?0:30});}
  add('Punya',v.Moon,v.Sun);add('Vidya',v.Sun,v.Moon);add('Yasas',v.Jupiter,v.Punya);add('Mitra',v.Jupiter,v.Punya,v.Venus);add('Mahatmya',v.Punya,v.Mars);add('Asha',v.Saturn,v.Mars);
  add('Samartha',E.LORDS[c.lagna.sign]==='Mars'?v.Jupiter:v.Mars,E.LORDS[c.lagna.sign]==='Mars'?v.Mars:v.lagnaLord);add('Bhratri',v.Jupiter,v.Saturn,L,true);add('Gaurava',v.Jupiter,v.Moon,v.Sun);
  add('Pitri',v.Saturn,v.Sun);add('Rajya',v.Saturn,v.Sun);add('Matri',v.Moon,v.Venus);add('Putra',v.Jupiter,v.Moon);add('Jeeva',v.Saturn,v.Jupiter);add('Karma',v.Mars,v.Mercury);add('Roga',L,v.Moon);add('Kali',v.Jupiter,v.Mars);add('Sastra',v.Jupiter,v.Saturn,v.Mercury);add('Bandhu',v.Mercury,v.Moon);add('Mrityu',house(8),v.Moon,L,true);add('Paradesa',house(9),lord(9),L,true);add('Artha',house(2),lord(2),L,true);add('Paradara',v.Venus,v.Sun);add('Vanik',v.Moon,v.Mercury);
  const light=day?'Sun':'Moon';add('Karyasiddhi',v.Saturn,v[light],p[E.LORDS[p[light].sign]].longitude,true);add('Vivaha',v.Venus,v.Saturn);add('Santapa',v.Saturn,v.Moon,house(6));add('Sraddha',v.Venus,v.Mars);add('Preeti',v.Sastra,v.Punya);add('Jadya',v.Mars,v.Saturn,v.Mercury);add('Vyapara',v.Mars,v.Saturn,L,true);add('Satru',v.Mars,v.Saturn);add('Jalapatana',105,v.Saturn);add('Bandhana',v.Punya,v.Saturn);add('Apamrityu',house(8),v.Mars);add('Labha',house(11),lord(11),L,true);
  return {status:'calculated',points,policy:'PVR28.8 Table74：日間A−B+C，夜間互換A/B，具名日夜不變例外另列；若C不在B順行至A弧內則加30°。十二宮度點為上升+30°步進。古典名稱不推定生死、出軌或疾病事實。'};
 }
 function harsha(c){const E=root.JYVedic,day=c.strength?.clock?.segment?.daytime,feminine=['Moon','Mercury','Venus','Saturn'],special={Sun:9,Moon:3,Mars:6,Mercury:1,Jupiter:11,Venus:5,Saturn:12};return K.map(k=>{const p=c.planets[k],f=feminine.includes(k),components={specialHouse:p.house===special[k]?5:0,ownOrExalt:p.dignity.exaltedSign||E.LORDS[p.sign]===k?5:0,genderHouse:(f?[1,2,3,7,8,9]:[4,5,6,10,11,12]).includes(p.house)?5:0,dayNight:typeof day==='boolean'?(day!==f?5:0):null};return {planet:k,components,total:Object.values(components).includes(null)?null:Object.values(components).reduce((s,v)=>s+v,0)};});}
 function patyayini(c,start,durationDays=365.2425){const order=K.concat('Lagna').map(planet=>({planet,krisamsa:planet==='Lagna'?c.lagna.degree:c.planets[planet].degree})).sort((a,b)=>a.krisamsa-b.krisamsa),max=order.at(-1).krisamsa,rows=order.map((r,i)=>({...r,patyamsa:r.krisamsa-(i?order[i-1].krisamsa:0)}));if(max===0)return {status:'undetermined',missing:['全部krisamsa零，比例分母無效'],periods:[]};let cursor=start;const periods=rows.map((r,i)=>{const length=durationDays*DAY*r.patyamsa/max,p={lord:r.planet,start:cursor,end:cursor+length,days:length/DAY,children:[]};cursor=p.end;let sub=p.start;for(let j=0;j<rows.length;j++){const z=rows[(i+j)%rows.length],end=sub+length*z.patyamsa/max;p.children.push({lord:z.planet,start:sub,end});sub=end;}return p;});return {system:'Patyayini',status:'calculated',yearDays:durationDays,ratioDenominator:max,ratios:rows,periods};}
 function solarPeriods(chart,slots,start,end,reference){const E=root.JYVedic,target=solar(chart,start);let solarOffset=0;const periods=[];let clocks=yearlyClocks.get(chart);if(!clocks){clocks=new Map();yearlyClocks.set(chart,clocks);}const clockKey=start+':'+end;if(!clocks.has(clockKey))clocks.set(clockKey,new Map([[0,start],[360,end]]));const memo=clocks.get(clockKey);function at(degrees){const k=Math.round(degrees*1e8)/1e8;if(!memo.has(k))memo.set(k,Date.parse(crossing(chart,E.norm(target+degrees),start+degrees/360*(end-start)).utc));return memo.get(k);}
  for(const slot of slots){if(solarOffset>=360-1e-8)break;const size=Math.min(slot.solarDegrees,360-solarOffset),fullSize=slot.fullSolarDegrees??slot.solarDegrees,elapsed=slot.elapsedSolarDegrees??0,fullStart=solarOffset-elapsed,p={lord:slot.lord,solarStart:solarOffset,solarDegrees:size,start:at(solarOffset),end:at(solarOffset+size),children:[],antardasaCalculation:slot.antardasaCalculation};
   let sub=fullStart;for(const ad of slot.children||[]){const stop=sub+fullSize*ad.fraction,lo=Math.max(solarOffset,sub),hi=Math.min(solarOffset+size,stop);if(hi>lo+1e-10)p.children.push({lord:ad.lord,start:at(lo),end:at(hi),solarStart:lo,solarDegrees:hi-lo,fullSolarStart:sub,fullSolarEnd:stop,clippedToAnnual:lo!==sub||hi!==stop});sub=stop;}
   solarOffset+=size;periods.push(p);}
  const maha=periods.find(p=>reference>=p.start&&reference<p.end)||null,antar=maha?.children.find(p=>reference>=p.start&&reference<p.end)||null;
  return {status:solarOffset>=360-1e-8?'calculated':'incomplete-model-window',periods,current:maha?{maha,antar}:null,solarDayPolicy:'一日=太陽實際前進1°，不當成固定24小時；副運保留原大運起點，首段已過與年末超出部分按年度窗裁切，不重新起副運'};
 }
 function chartForPeriod(natal,period,muntha,yearLord=null,kind='monthly'){
  const E=root.JYVedic,c=E.compute({...natal.input,utc:period.start,reference:period.start,civil:null,uncertaintyMinutes:0,transitRules:false,tajaka:false}),rules=root.JYVedicTajakaRules?root.JYVedicTajakaRules.compute(c,natal,muntha):null,start=Date.parse(period.start),p=patyayini(c,start,(Date.parse(period.endExclusive)-start)/DAY);
  const reference=Date.parse(natal.input.reference),maha=p.periods.find(z=>reference>=z.start&&reference<z.end)||null;p.current=maha?{maha,antar:maha.children.find(z=>reference>=z.start&&reference<z.end)||null}:null;
  return {kind,window:period,chart:c,harsha:harsha(c),sahams:sahams(c),ruleLedger:rules,monthLord:kind==='monthly'&&rules&&yearLord?root.JYVedicTajakaRules.yearLord(c,natal,muntha,rules.panchavargeeya.profiles[rules.profile],yearLord):null,patyayini:p,policy:'本次參照時刻所屬月盤／2.5°段實際完整重算；使用出生地與原年度Muntha，不以2.5°逐月推動Muntha。其餘段可按相同API和既列UTC起點選取；時間邊界列表不是已預算所有段內盤面。月／段Patyayini依該真實期間比例壓縮，與年度365.2425日規則分列。'};
 }
 function compute(chart,options={}){
  if(chart.input.unknownTime)return {status:'insufficient-data',missing:['confirmed-birth-time'],annual:null,months:[],sixtyHours:[]};
  const E=root.JYVedic,birth=new Date(chart.input.utc),reference=Date.parse(chart.input.reference);if(reference<+birth)return {status:'before-birth',annual:null,months:[],sixtyHours:[]};
  let year=new Date(reference).getUTCFullYear(),guess=y=>Date.UTC(y,birth.getUTCMonth(),birth.getUTCDate(),birth.getUTCHours(),birth.getUTCMinutes(),birth.getUTCSeconds()),ret=crossing(chart,chart.planets.Sun.longitude,guess(year));if(year===birth.getUTCFullYear()&&Math.abs(Date.parse(ret.utc)-Number(birth))<1000)ret={...ret,utc:birth.toISOString()};if(Date.parse(ret.utc)>reference)ret=crossing(chart,chart.planets.Sun.longitude,guess(--year));
  const start=Date.parse(ret.utc),next=crossing(chart,chart.planets.Sun.longitude,guess(year+1)),end=Date.parse(next.utc),age=year-birth.getUTCFullYear(),annual=E.compute({...chart.input,utc:ret.utc,reference:ret.utc,civil:null,uncertaintyMinutes:0,transitRules:false,tajaka:false}),muntha=mod(chart.lagna.sign+age,12);
  const months=Array.from({length:13},(_,i)=>i===0?ret:i===12?next:crossing(chart,chart.planets.Sun.longitude+i*30,start+(end-start)*i/12)).slice(0,12).map((point,i,all)=>({month:i+1,start:point.utc,endExclusive:i===11?next.utc:all[i+1].utc,target:point.target}));
  const sixtyHours=Array.from({length:145},(_,i)=>i===0?ret:i===144?next:crossing(chart,chart.planets.Sun.longitude+i*2.5,start+(end-start)*i/144)).slice(0,144).map((point,i,all)=>({index:i+1,month:Math.floor(i/12)+1,part:i%12+1,start:point.utc,endExclusive:i===143?next.utc:all[i+1].utc,target:point.target}));
  const first=mod(O.indexOf(chart.planets.Moon.nakshatra.lord)+age,9),remain=1-chart.planets.Moon.nakshatra.fraction,muddaSlots=Array.from({length:10},(_,i)=>{const j=mod(first+i,9);return {lord:O[j],solarDegrees:Y[j]*3*(i===0?remain:1),fullSolarDegrees:Y[j]*3,elapsedSolarDegrees:i===0?Y[j]*3*(1-remain):0,children:Array.from({length:9},(_,n)=>({lord:O[mod(j+n,9)],fraction:Y[mod(j+n,9)]/120}))};}),mudda={system:'Mudda-VarshaVimshottari',firstLord:O[first],natalNakshatraFractionRemaining:remain,...solarPeriods(chart,muddaSlots,start,end,reference)};
  const narayana={};for(const [d,v]of Object.entries(annual.vargas)){const cp=root.JYVedicCompletion,ps=cp.projectedPlanets(annual,v),seedSign=mod(muntha+(+d-1)%12,12),selection=+d===1?null:cp.coLord(annual.planets,seedSign,'dasha'),seed=+d===1?muntha:selection.winner?ps[selection.winner].sign:null,model=cp.rasiDasha(annual,ps,seed),slots=model.periods.slice(0,24).map(p=>({lord:p.lord,solarDegrees:p.years*3,antardasaCalculation:p.antardasaCalculation,children:p.children.map(a=>({lord:a.lord,fraction:(a.end-a.start)/(p.end-p.start)}))}));narayana[d]={system:'VarshaNarayana-D'+d,division:+d,seed:{muntha,seedSign,selection,virtualLagna:seed},modelStatus:model.status,selection:model.selection,lengths:model.lengths,progression:model.progression,...solarPeriods(chart,slots,start,end,reference)};}
  const pats=patyayini(annual,start);const patMD=pats.periods.find(p=>reference>=p.start&&reference<p.end)||null;pats.current=patMD?{maha:patMD,antar:patMD.children.find(p=>reference>=p.start&&reference<p.end)||null}:null;
  const ruleLedger=root.JYVedicTajakaRules?root.JYVedicTajakaRules.compute(annual,chart,muntha):{status:'module-unavailable'},month=months.find(p=>Date.parse(p.start)<=reference&&reference<Date.parse(p.endExclusive)),segment=sixtyHours.find(p=>Date.parse(p.start)<=reference&&reference<Date.parse(p.endExclusive)),currentMonth=month?chartForPeriod(chart,month,muntha,ruleLedger.yearLord?.winner,'monthly'):null,currentSixtyHour=segment?chartForPeriod(chart,segment,muntha,null,'sixty-hour'):null;
  return {version:'20261003tajaka1',status:'calculated',profile:'PVR27_28_HARSHA_SAHAMS_30_ANNUAL_DASAS',source,return:ret,nextReturn:next,completedYears:age,window:{start:ret.utc,endExclusive:next.utc},annual:{utc:ret.utc,input:annual.input,policy:annual.policy,julianDay:annual.julianDay,relationships:annual.relationships,lagna:annual.lagna,planets:annual.planets,houses:annual.houses,vargas:annual.vargas,aspects:annual.aspects,strength:annual.strength},muntha:{sign:muntha,lord:E.LORDS[muntha],fromAnnualLagna:mod(muntha-annual.lagna.sign,12)+1},ruleLedger,currentMonth,currentSixtyHour,harsha:harsha(annual),sahams:sahams(annual),months,sixtyHours,dashas:{patyayini:pats,mudda,varshaNarayana:narayana},policy:'PVR具名歲時算術：出生地坐標、恆星太陽同度回歸，12個30°月與144個2.5°段均實際求根；60小時是古典名稱，非固定時長。Patyayini採原文365.2425民用日，Mudda與VarshaNarayana採真實太陽度日，分列不同界線。大副運及各分盤種子依具名規則。Harsha與36Sahams均保留分量；未把年度盤當原本命或把古典象義當實際事件。'};
 }
 root.JYVedicTajaka=Object.freeze({compute,chartForPeriod,crossing,solar,sahams,harsha,patyayini,solarPeriods,version:'20261003tajaka1'});
})(typeof window==='undefined'?globalThis:window);
