/*! bazi-suite.js — 靜月之光八字完整功能套件 UI v1.0.1 (2026-06-26)
 *  單盤多主題／八種情境雙人合盤／本地五軸32型人格／歷史紀錄與匯出。
 */
(function () {
  'use strict';

  var GOLD='#c9a84c', BG='#090a10', PANEL='#13151e', TEXT='#eee7d7', MUTED='rgba(238,231,215,.58)';
  var AI_LINKS=[
    ['ChatGPT','https://chatgpt.com/'],['Gemini','https://gemini.google.com/app'],['Claude','https://claude.ai/new'],
    ['Grok','https://grok.com/'],['DeepSeek','https://chat.deepseek.com/'],['Kimi','https://kimi.moonshot.cn/'],
    ['豆包','https://www.doubao.com/'],['Meta AI','https://www.meta.ai/'],['Copilot','https://copilot.microsoft.com/'],['Perplexity','https://www.perplexity.ai/']
  ];
  var state={tab:'single',lens:'general',scenario:'marriage',single:null,compat:null,personality:null,tools:{solar:null,reverse:null},prompt:'',exportData:null};
  var drafts={};
  var screen=null, legacyOpen=window._baziStandaloneOpen || null;
  var STORE_KEY='jy_bazi_suite_history_v1';

  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function arr(x){return Array.isArray(x)?x:[];}
  function fmt(x,f){return x==null||x===''?(f||'—'):String(x);}
  function byId(id){return document.getElementById(id);}
  function toast(msg,bad){
    var t=byId('bzs-toast'); if(!t)return;
    t.textContent=msg;t.className='bzs-toast show'+(bad?' bad':'');
    clearTimeout(toast._t);toast._t=setTimeout(function(){t.className='bzs-toast';},2300);
  }
  function icon(title,body){return '<div class="bzs-empty"><div class="bzs-moon">☾</div><b>'+esc(title)+'</b><p>'+esc(body)+'</p></div>';}

  function injectCss(){
    if(byId('bzs-style'))return;
    var st=document.createElement('style');st.id='bzs-style';st.textContent=[
      '#bzs-screen{display:none;position:fixed;inset:0;z-index:100100;background:'+BG+';color:'+TEXT+';overflow:auto;-webkit-overflow-scrolling:touch;font-family:"Noto Serif TC",system-ui,sans-serif}',
      '#bzs-screen *{box-sizing:border-box}.bzs-shell{max-width:680px;margin:auto;min-height:100%;padding:0 12px 90px}',
      '.bzs-top{position:sticky;top:0;z-index:9;background:linear-gradient('+BG+' 72%,rgba(9,10,16,0));padding:12px 0 20px}.bzs-bar{display:flex;align-items:center;gap:10px}.bzs-back{border:0;background:transparent;color:'+MUTED+';font-size:21px;padding:8px;cursor:pointer}.bzs-brand{flex:1}.bzs-brand b{display:block;color:'+GOLD+';letter-spacing:4px;font-size:17px}.bzs-brand small{color:'+MUTED+'}.bzs-legacy{border:1px solid rgba(201,168,76,.25);background:rgba(201,168,76,.06);color:'+GOLD+';border-radius:10px;padding:7px 9px;font-size:11px;cursor:pointer}',
      '.bzs-tabs{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:12px;padding:4px;border-radius:14px;background:#11131a}.bzs-tab{border:0;border-radius:10px;background:transparent;color:'+MUTED+';padding:9px 3px;font:inherit;font-size:12px;cursor:pointer}.bzs-tab.active{background:rgba(201,168,76,.14);color:#ffe4a3;box-shadow:inset 0 0 0 1px rgba(201,168,76,.28)}',
      '.bzs-card{background:'+PANEL+';border:1px solid rgba(201,168,76,.16);border-radius:16px;padding:14px;margin:10px 0;box-shadow:0 10px 30px rgba(0,0,0,.18)}.bzs-card h2,.bzs-card h3{margin:0 0 10px;color:'+GOLD+';letter-spacing:1px}.bzs-card h2{font-size:17px}.bzs-card h3{font-size:14px}.bzs-card p{line-height:1.75;margin:7px 0;color:rgba(238,231,215,.78);font-size:13px}',
      '.bzs-note{padding:10px 12px;border-left:3px solid '+GOLD+';background:rgba(201,168,76,.06);border-radius:6px;color:rgba(238,231,215,.68);font-size:12px;line-height:1.65}.bzs-warning{border-left-color:#c87569;background:rgba(200,117,105,.08)}',
      '.bzs-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.bzs-grid.one{grid-template-columns:1fr}.bzs-field{display:flex;flex-direction:column;gap:5px}.bzs-field.full{grid-column:1/-1}.bzs-field label{font-size:11px;color:'+MUTED+'}.bzs-input,.bzs-select,.bzs-text{width:100%;border:1px solid rgba(201,168,76,.25);background:#0d0f16;color:'+TEXT+';border-radius:11px;padding:11px;font:inherit;font-size:14px;outline:none}.bzs-input:focus,.bzs-select:focus,.bzs-text:focus{border-color:'+GOLD+';box-shadow:0 0 0 3px rgba(201,168,76,.08)}.bzs-text{min-height:82px;resize:vertical;line-height:1.55}.bzs-select option{background:#11131a}.bzs-check{display:flex;align-items:center;gap:7px;color:'+MUTED+';font-size:12px;margin-top:6px}.bzs-check input{accent-color:'+GOLD+'}',
      '.bzs-choice{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.bzs-choice.three{grid-template-columns:repeat(3,1fr)}.bzs-choice.six{grid-template-columns:repeat(3,1fr)}.bzs-chip{border:1px solid rgba(255,255,255,.08);background:#0e1017;color:'+MUTED+';padding:10px 7px;border-radius:11px;font:inherit;font-size:12px;cursor:pointer}.bzs-chip.active{border-color:rgba(201,168,76,.55);background:rgba(201,168,76,.11);color:#ffe4a3}',
      '.bzs-primary{width:100%;border:1px solid rgba(201,168,76,.6);background:linear-gradient(135deg,rgba(201,168,76,.23),rgba(201,168,76,.07));color:#ffe1a0;border-radius:13px;padding:13px;font:inherit;font-weight:700;letter-spacing:2px;cursor:pointer}.bzs-primary:active,.bzs-action:active{transform:scale(.98)}.bzs-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin:10px 0}.bzs-action{border:1px solid rgba(201,168,76,.25);background:#10121a;color:'+TEXT+';border-radius:11px;padding:10px;font:inherit;font-size:12px;cursor:pointer;text-decoration:none;text-align:center}',
      '.bzs-lenses{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.bzs-lens{min-height:54px}.bzs-scenarios{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}',
      '.bzs-person-head{display:flex;align-items:center;gap:9px;margin-bottom:8px}.bzs-badge{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(201,168,76,.45);color:'+GOLD+';background:rgba(201,168,76,.08);font-weight:bold}.bzs-person-head h3{margin:0}.bzs-person-head small{display:block;color:'+MUTED+';font-size:11px}',
      '.bzs-pillars{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.bzs-pillar{text-align:center;padding:9px 3px;border-radius:11px;background:#0c0e15;border:1px solid rgba(201,168,76,.18)}.bzs-pillar small{display:block;color:'+MUTED+';font-size:10px}.bzs-pillar strong{display:block;color:#ffe2a0;font-size:20px;letter-spacing:2px;margin:4px 0}.bzs-pillar em{font-style:normal;color:rgba(238,231,215,.65);font-size:10px}',
      '.bzs-kv{display:grid;grid-template-columns:auto 1fr;gap:6px 10px;font-size:12px;line-height:1.6}.bzs-kv dt{color:'+MUTED+'}.bzs-kv dd{margin:0;color:rgba(238,231,215,.88)}.bzs-tags{display:flex;flex-wrap:wrap;gap:5px}.bzs-tag{font-size:11px;border:1px solid rgba(201,168,76,.2);color:rgba(238,231,215,.72);border-radius:999px;padding:4px 7px;background:rgba(201,168,76,.04)}.bzs-tag.tension{border-color:rgba(207,105,93,.36);background:rgba(207,105,93,.08)}.bzs-tag.support{border-color:rgba(104,174,139,.35);background:rgba(104,174,139,.08)}',
      '.bzs-luck{overflow:auto}.bzs-luck table{width:100%;border-collapse:collapse;min-width:550px;font-size:11px}.bzs-luck th,.bzs-luck td{padding:8px;border-bottom:1px solid rgba(255,255,255,.06);text-align:left}.bzs-luck th{color:'+GOLD+'}.bzs-luck tr.current{background:rgba(201,168,76,.07)}',
      '.bzs-rel{padding:9px 10px;border-radius:10px;background:#0c0e15;margin:6px 0;font-size:12px;line-height:1.55;border-left:2px solid rgba(201,168,76,.4)}.bzs-rel.tension{border-left-color:#c96e62}.bzs-rel.support{border-left-color:#6da989}',
      '.bzs-type{position:relative;overflow:hidden;text-align:center;padding:25px 16px;background:radial-gradient(circle at 50% 0,rgba(201,168,76,.2),transparent 50%),#10121a}.bzs-type:before{content:"";position:absolute;inset:8px;border:1px solid rgba(201,168,76,.25);border-radius:12px;pointer-events:none}.bzs-type .code{font-size:13px;letter-spacing:7px;color:'+GOLD+'}.bzs-type h2{font-size:23px;margin:10px 0}.bzs-type .axes{color:rgba(238,231,215,.7);font-size:12px}.bzs-axis{display:grid;grid-template-columns:60px 1fr 60px;gap:8px;align-items:center;margin:10px 0;font-size:11px;color:'+MUTED+'}.bzs-track{height:7px;border-radius:9px;background:#090b11;position:relative}.bzs-dot{position:absolute;top:-3px;width:13px;height:13px;border-radius:50%;background:'+GOLD+';box-shadow:0 0 10px rgba(201,168,76,.5)}',
      '.bzs-history{display:flex;gap:8px;align-items:flex-start}.bzs-history-main{flex:1}.bzs-history time{color:'+MUTED+';font-size:10px}.bzs-history button{border:0;background:transparent;color:#c87569;cursor:pointer;font-size:17px}',
      '.bzs-empty{text-align:center;padding:45px 20px;color:'+MUTED+'}.bzs-empty .bzs-moon{font-size:46px;color:'+GOLD+';margin-bottom:8px}.bzs-empty p{max-width:360px;margin:8px auto;line-height:1.65}.bzs-toast{position:fixed;left:50%;bottom:25px;transform:translate(-50%,20px);opacity:0;pointer-events:none;background:#1c201e;border:1px solid rgba(104,174,139,.45);padding:10px 15px;border-radius:999px;color:#dcf4e6;font-size:12px;transition:.25s;z-index:100300}.bzs-toast.show{opacity:1;transform:translate(-50%,0)}.bzs-toast.bad{border-color:rgba(207,105,93,.5);color:#f6d4cf;background:#241817}',
      '.bzs-ai{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.bzs-ai a{color:'+TEXT+';text-decoration:none;border:1px solid rgba(201,168,76,.2);border-radius:10px;padding:9px;text-align:center;font-size:11px;background:#0d0f16}',
      '@media(max-width:460px){.bzs-grid{grid-template-columns:1fr}.bzs-field.full{grid-column:auto}.bzs-lenses,.bzs-choice.six{grid-template-columns:repeat(2,1fr)}.bzs-actions{grid-template-columns:1fr 1fr}.bzs-tabs{grid-template-columns:repeat(4,1fr)}.bzs-tab{font-size:11px}.bzs-shell{padding-left:9px;padding-right:9px}}',
      '@media print{body>*:not(#bzs-screen){display:none!important}#bzs-screen{display:block!important;position:static!important;overflow:visible!important;background:white!important;color:black!important}.bzs-top,.bzs-actions,.bzs-ai,.bzs-primary,.bzs-back,.bzs-legacy{display:none!important}.bzs-card{break-inside:avoid;background:white!important;color:black!important;border-color:#bbb!important;box-shadow:none!important}.bzs-card p,.bzs-kv dd,.bzs-pillar em{color:#333!important}}'
    ].join('');document.head.appendChild(st);
  }

  function getScreen(){
    if(screen)return screen;injectCss();screen=document.createElement('div');screen.id='bzs-screen';screen.innerHTML='<div class="bzs-shell"><div class="bzs-top"><div class="bzs-bar"><button class="bzs-back" data-act="close">‹</button><div class="bzs-brand"><b>八字全域分析</b><small>精確排盤・多主題・情境合盤・人格卡</small></div><button class="bzs-legacy" data-act="legacy">返回原版單盤</button></div><div class="bzs-tabs"></div></div><main id="bzs-main"></main></div><div id="bzs-toast" class="bzs-toast"></div>';
    document.body.appendChild(screen);screen.addEventListener('click',onClick);screen.addEventListener('change',onChange);screen.addEventListener('input',onInput);return screen;
  }

  function tabsHtml(){var tabs=[['single','單人'],['compat','合盤'],['personality','人格'],['tools','工具'],['history','紀錄']];return tabs.map(function(x){return '<button class="bzs-tab '+(state.tab===x[0]?'active':'')+'" data-tab="'+x[0]+'">'+x[1]+'</button>';}).join('');}
  function render(){cacheAllForms();var s=getScreen();s.querySelector('.bzs-tabs').innerHTML=tabsHtml();var main=byId('bzs-main');if(state.tab==='single')main.innerHTML=renderSingle();else if(state.tab==='compat')main.innerHTML=renderCompat();else if(state.tab==='personality')main.innerHTML=renderPersonality();else if(state.tab==='tools')main.innerHTML=renderTools();else main.innerHTML=renderHistory();afterRender();s.scrollTop=0;}

  function locationFields(prefix){
    return '<div class="bzs-field"><label>國家／地區</label><select id="'+prefix+'-country" class="bzs-select" data-country="'+prefix+'"></select></div><div class="bzs-field"><label>出生城市</label><select id="'+prefix+'-city" class="bzs-select"><option value="">先選國家</option></select></div>';
  }
  function personForm(prefix,title,role,defaults){defaults=defaults||{};return '<section class="bzs-card"><div class="bzs-person-head"><span class="bzs-badge">'+esc(title)+'</span><div><h3>'+esc(role)+'</h3><small>各自獨立校正真太陽時與起運</small></div></div><div class="bzs-grid">'+
    '<div class="bzs-field"><label>稱呼（選填）</label><input id="'+prefix+'-name" class="bzs-input" placeholder="例如：A／本人"></div>'+
    '<div class="bzs-field"><label>性別</label><select id="'+prefix+'-gender" class="bzs-select"><option value="male">男</option><option value="female">女</option></select></div>'+
    '<div class="bzs-field"><label>國曆出生日期</label><input id="'+prefix+'-date" type="date" min="1900-01-01" max="2099-12-31" class="bzs-input" value="'+esc(defaults.date||'')+'"></div>'+
    '<div class="bzs-field"><label>民用出生時間</label><input id="'+prefix+'-time" type="time" class="bzs-input" value="'+esc(defaults.time||'12:00')+'"><label class="bzs-check"><input id="'+prefix+'-unknown" type="checkbox"> 不知道時辰（以12:00暫排並降級）</label></div>'+
    locationFields(prefix)+
    '<div class="bzs-field full"><label>23時換日流派</label><select id="'+prefix+'-boundary" class="bzs-select"><option value="ZI_HOUR_23">23:00 子初換日</option><option value="MIDNIGHT_00">00:00 午夜換日</option></select></div></div></section>';}

  function renderSingle(){
    if(state.single)return resultSingle();
    var lenses=Object.keys(BaziSuiteCore.lenses).map(function(k){var x=BaziSuiteCore.lenses[k];return '<button class="bzs-chip bzs-lens '+(state.lens===k?'active':'')+'" data-lens="'+k+'">'+esc(x.name)+'</button>';}).join('');
    return '<div class="bzs-card"><h2>單人八字分析</h2><p>同一張精確命盤可切換純排盤、綜合、事業、財富、感情與流年，不必重複輸入。</p><div class="bzs-lenses">'+lenses+'</div></div>'+personForm('s','命','命主',{time:'12:00'})+
      '<div class="bzs-card"><h3>問題（選填）</h3><textarea id="s-question" class="bzs-text" placeholder="例如：我經濟壓力何時較可能減輕？"></textarea><div class="bzs-note">提示詞會區分可重算的排盤事實與流派模型，不把分數寫成機率或必然事件。</div></div><button class="bzs-primary" data-act="cast-single">建立完整命盤與提示詞</button>';
  }

  function renderCompat(){
    if(state.compat)return resultCompat();
    var scenarios=BaziSuiteCore.scenarios.map(function(x){return '<button class="bzs-chip '+(state.scenario===x.id?'active':'')+'" data-scenario="'+x.id+'">'+esc(x.name)+'</button>';}).join('');
    var sc=BaziSuiteCore.scenarios.find(function(x){return x.id===state.scenario;})||BaziSuiteCore.scenarios[0];
    return '<div class="bzs-card"><h2>雙人情境合盤</h2><p>先指定關係角色，再比較雙向十神、日柱／夫妻宮、跨盤干支、五行互補與雙方大運流年，不提供虛假的單一配對分數。</p><div class="bzs-scenarios">'+scenarios+'</div><div class="bzs-note" style="margin-top:10px">本情境焦點：'+esc(sc.focus)+'</div></div>'+personForm('a','A',sc.roleA,{time:'12:00'})+personForm('b','B',sc.roleB,{time:'12:00'})+
      '<div class="bzs-card"><h3>關係問題（選填）</h3><textarea id="c-question" class="bzs-text" placeholder="例如：我們適合長期合作嗎？權責如何分配？"></textarea></div><button class="bzs-primary" data-act="cast-compat">建立雙向合盤</button>';
  }

  function renderPersonality(){
    if(state.personality)return resultPersonality();
    return '<div class="bzs-card"><h2>靜月五軸 32 型人格</h2><p>以出生資料轉成可分享的人格卡，作為進入完整八字前的輕量入口。</p><div class="bzs-note warning">這是本站自行建立的五軸模型，不是 OpenFate BZTI，也沒有使用其未公開演算法；不屬心理診斷。</div></div>'+personForm('p','型','人格測試',{time:'12:00'})+
      '<div class="bzs-card"><h3>想觀察的情境（選填）</h3><textarea id="p-question" class="bzs-text" placeholder="例如：我在工作壓力下為什麼會變得很安靜？"></textarea></div><button class="bzs-primary" data-act="cast-personality">生成 32 型人格卡</button>';
  }

  function renderTools(){
    var now=new Date().getFullYear(),solar=state.tools.solar,rev=state.tools.reverse;
    var solarResult=solar?'<section class="bzs-card"><h3>真太陽時計算結果</h3><dl class="bzs-kv"><dt>民用時間</dt><dd>'+esc(solar.civilDateTime||solar.inputCivilDateTime||'—')+'</dd><dt>真太陽時</dt><dd>'+esc(solar.trueSolarDateTime)+'</dd><dt>經度修正</dt><dd>'+esc(Number(solar.longitudeCorrectionMinutes||0).toFixed(2))+' 分</dd><dt>均時差</dt><dd>'+esc(Number(solar.equationOfTimeMinutes||0).toFixed(2))+' 分</dd><dt>DST</dt><dd>'+esc(fmt(solar.dstOffsetMinutes,0))+' 分</dd><dt>時區來源</dt><dd>'+esc(fmt(solar.timezoneSource))+'／'+esc(fmt(solar.civilTimeStatus))+'</dd></dl><div class="bzs-note">真太陽時只校正時間基準，不等同命理解讀。</div></section>':'';
    var revResult='';if(rev){revResult='<section class="bzs-card"><h3>四柱反查候選（'+rev.matches.length+'）</h3><div class="bzs-note warning">'+esc(rev.note)+'</div>'+(rev.matches.length?'<div class="bzs-luck"><table><thead><tr><th>公曆候選</th><th>時辰範圍</th><th>四柱</th></tr></thead><tbody>'+rev.matches.map(function(x){return '<tr><td>'+esc(x.datetime)+'</td><td>'+esc(x.hourRange)+'</td><td>'+esc(x.pillars)+'</td></tr>';}).join('')+'</tbody></table></div>':'<p>指定年份範圍內沒有找到候選。請確認四柱、換日流派或擴大年份範圍。</p>')+'<div class="bzs-actions"><button class="bzs-action" data-act="download-tool-json">下載結果 JSON</button><button class="bzs-action" data-act="clear-tools">清除結果</button></div></section>';}
    return '<section class="bzs-card"><h2>曆法與反查工具</h2><p>補齊精確真太陽時計算與「由四柱找公曆候選」功能。反查只作候選搜尋，不能跳過地點與真太陽時複核。</p><div class="bzs-note">政策：有地點時優先真太陽時；預設23:00子初換日；流年以立春為界；大運採 [起點,下一起點) 半開區間。</div></section>'+      '<section class="bzs-card"><h3>真太陽時計算</h3><div class="bzs-grid"><div class="bzs-field"><label>民用日期</label><input id="u-date" type="date" class="bzs-input"></div><div class="bzs-field"><label>民用時間</label><input id="u-time" type="time" step="1" value="12:00:00" class="bzs-input"></div>'+locationFields('u')+'</div><button class="bzs-primary" data-act="calc-solar" style="margin-top:10px">計算真太陽時</button></section>'+solarResult+      '<section class="bzs-card"><h3>四柱反查公曆候選</h3><div class="bzs-grid"><div class="bzs-field full"><label>四柱（年 月 日 時）</label><input id="r-bazi" class="bzs-input" placeholder="例如：戊寅 己未 己卯 辛未"></div><div class="bzs-field"><label>起始年</label><input id="r-start" type="number" min="1" max="2300" value="1900" class="bzs-input"></div><div class="bzs-field"><label>結束年</label><input id="r-end" type="number" min="1" max="2300" value="'+now+'" class="bzs-input"></div><div class="bzs-field"><label>換日政策</label><select id="r-boundary" class="bzs-select"><option value="ZI_HOUR_23">23:00 子初換日</option><option value="MIDNIGHT_00">00:00 午夜換日</option></select></div><div class="bzs-field"><label>最多候選</label><input id="r-limit" type="number" min="1" max="200" value="50" class="bzs-input"></div></div><button class="bzs-primary" data-act="reverse-bazi" style="margin-top:10px">開始反查候選</button><div id="r-progress" class="bzs-note" style="display:none;margin-top:8px">正在依年柱週期縮小範圍並核對四柱…</div></section>'+revResult;
  }

  function pillarCards(chart){var P=chart.pillars||{},G=chart.gods||{},C=chart.cangGan||{},CS=chart.cs||{};return '<div class="bzs-pillars">'+['year','month','day','hour'].map(function(k,i){var p=P[k]||{},g=G[k]||{};return '<div class="bzs-pillar"><small>'+['年柱','月柱','日柱','時柱'][i]+'</small><em>'+esc(g.gan||'—')+'</em><strong>'+esc((p.gan||'')+(p.zhi||''))+'</strong><em>'+esc(arr(C[k]).join('、')||'—')+'<br>'+esc(CS[k]||'')+'</em></div>';}).join('')+'</div>';}
  function summaryCard(chart,meta,title){var cur=arr(chart.dayun).find(function(x){return x.isCurrent;}),animals={子:'鼠',丑:'牛',寅:'虎',卯:'兔',辰:'龍',巳:'蛇',午:'馬',未:'羊',申:'猴',酉:'雞',戌:'狗',亥:'豬'},yz=chart.pillars&&chart.pillars.year&&chart.pillars.year.zhi;return '<section class="bzs-card"><h2>'+esc(title||meta.name||'命盤')+'</h2>'+pillarCards(chart)+'<dl class="bzs-kv" style="margin-top:12px"><dt>真太陽時</dt><dd>'+esc(meta.solarInfo&&meta.solarInfo.trueSolarDateTime||'未校正')+'</dd><dt>生肖／重量</dt><dd>'+esc(animals[yz]||'—')+'；'+esc(chart.chenggu&&chart.chenggu.display||'未計得')+'（傳統稱骨末位參考）</dd><dt>日主／旺衰</dt><dd>'+esc(chart.dm+'（'+chart.dmEl+'）・'+fmt(chart.strongLevel))+'</dd><dt>扶抑候選</dt><dd>喜 '+esc(arr(chart.wuxingStance&&chart.wuxingStance.xi||chart.fav).join('、')||'—')+'；忌 '+esc(arr(chart.wuxingStance&&chart.wuxingStance.ji||chart.unfav).join('、')||'—')+'</dd><dt>'+(meta.unknown?'暫定起運':'起運')+'</dt><dd>'+esc(fmt(chart.qiyun&&chart.qiyun.startAgeText))+'；'+esc(fmt(chart.qiyun&&chart.qiyun.startDate))+(meta.unknown?'（12:00暫排）':'')+'</dd><dt>現行大運</dt><dd>'+esc(cur?cur.gz+'（'+cur.startDate+'～'+cur.endDateExclusive+'）':'未判定')+'</dd></dl>'+(meta.unknown?'<div class="bzs-note warning">時辰未知：時柱、神煞、精確起運與時柱跨盤作用已標示降級。</div>':'')+'</section>';}
  function interactionsCard(chart){var xs=arr(chart.branchInteractions).concat(arr(chart.tianGanHe).map(function(x){return {type:'天干五合',desc:x.zh||x.pair,effect:'合化狀態 '+fmt(x.transformationStatus,'待審')};}));return '<section class="bzs-card"><h3>原局干支作用</h3>'+(xs.length?xs.map(function(x){return '<div class="bzs-rel">'+esc(x.type)+'｜'+esc(x.desc||x.description)+'<br><span style="color:'+MUTED+'">'+esc(x.effect||'配對存在，吉凶另審')+'</span></div>';}).join(''):'<p>未偵測到需特別列出的作用；不代表命局沒有生剋。</p>')+'</section>';}
  function luckTable(chart){var ds=arr(chart.dayun).filter(function(x){return x.gz&&x.gz!=='小運';});return '<section class="bzs-card"><h3>精確大運</h3><div class="bzs-luck"><table><thead><tr><th>大運</th><th>區間</th><th>十神</th><th>模型標記</th></tr></thead><tbody>'+ds.map(function(x){return '<tr class="'+(x.isCurrent?'current':'')+'"><td>'+esc(x.gz)+(x.isCurrent?' ★':'')+'</td><td>'+esc(x.startDate)+'<br>～ '+esc(x.endDateExclusive)+'</td><td>'+esc(fmt(x.god))+'／'+esc(fmt(x.zGod))+'</td><td>'+esc(fmt(x.level))+'</td></tr>';}).join('')+'</tbody></table></div><div class="bzs-note">等級只作模型內相對排序；大運干支十年共同作用，所有交界以完整日期時間判定。</div></section>';}
  function promptActions(){return '<section class="bzs-card"><h3>提示詞與匯出</h3><div class="bzs-actions"><button class="bzs-action" data-act="copy">複製完整提示詞</button><button class="bzs-action" data-act="download-prompt">下載提示詞 TXT</button><button class="bzs-action" data-act="download-json">下載資料 JSON</button><button class="bzs-action" data-act="print">列印／存 PDF</button><button class="bzs-action" data-act="share">生成分享卡</button><button class="bzs-action" data-act="reset-current">重新輸入</button></div><div class="bzs-ai">'+AI_LINKS.map(function(x){return '<a href="'+x[1]+'" target="_blank" rel="noopener" data-ai="1">'+x[0]+'</a>';}).join('')+'</div><p style="font-size:11px;color:'+MUTED+'">點 AI 前會先複製提示詞；若瀏覽器禁止剪貼簿，請使用「複製完整提示詞」。</p></section>';}

  function resultSingle(){var r=state.single;return summaryCard(r.chart,r.meta,BaziSuiteCore.lenses[r.lens].name)+interactionsCard(r.chart)+luckTable(r.chart)+promptActions();}
  function relationClass(x){return ['CLASH','HARM','DESTRUCTION','PUNISHMENT','SELF_PUNISHMENT'].indexOf(x.typeCode)>=0?'tension':['STEM_COMBINATION','SIX_COMBINATION','CROSS_TRINE','CROSS_DIRECTIONAL'].indexOf(x.typeCode)>=0?'support':'';}
  function resultCompat(){var r=state.compat,c=r.comp,rels=arr(c.stemRelations).filter(function(x){return x.typeCode==='STEM_COMBINATION';}).concat(c.branchRelations,c.groupRelations);return '<section class="bzs-card"><h2>'+esc(c.scenario.name)+'合盤主視圖</h2><p>'+esc(c.evidenceSummary.signal)+'。此為證據整理，不是成功率。</p>'+(c.uncertainty&&c.uncertainty.hourRelationsExcluded?'<div class="bzs-note warning">'+esc(c.uncertainty.note)+'</div>':'')+'<div class="bzs-tags"><span class="bzs-tag support">支持／牽連 '+c.evidenceSummary.supportCount+'</span><span class="bzs-tag tension">張力／磨合 '+c.evidenceSummary.tensionCount+'</span><span class="bzs-tag">不設總分</span></div></section>'+summaryCard(r.chartA,r.metaA,c.scenario.roleA)+summaryCard(r.chartB,r.metaB,c.scenario.roleB)+
    '<section class="bzs-card"><h3>日主與日柱核心</h3><dl class="bzs-kv"><dt>A → B</dt><dd>'+esc(c.dayMasters.aToB.label)+'</dd><dt>B → A</dt><dd>'+esc(c.dayMasters.bToA.label)+'</dd><dt>日柱</dt><dd>A '+esc(c.spousePalace.aDayPillar)+'；B '+esc(c.spousePalace.bDayPillar)+'</dd><dt>情境焦點</dt><dd>'+esc(c.scenario.focus)+'</dd></dl><div class="bzs-note">方向性生剋與十神不能互換；婚戀以日支重要，但仍不能凌駕完整兩盤與現實互動。</div></section>'+ 
    '<section class="bzs-card"><h3>跨盤干支作用</h3>'+(rels.length?rels.map(function(x){return '<div class="bzs-rel '+relationClass(x)+'">'+esc(x.description)+'</div>';}).join(''):'<p>未偵測到明顯的跨盤合沖刑害破；仍需看十神、五行立場與現實情境。</p>')+'</section>'+ 
    '<section class="bzs-card"><h3>雙向十神映射</h3><p><b style="color:'+GOLD+'">A 看 B：</b>'+c.directionalTenGods.aViewsB.map(function(x){return esc(x.partnerStem+'＝'+x.tenGod);}).join('・')+'</p><p><b style="color:'+GOLD+'">B 看 A：</b>'+c.directionalTenGods.bViewsA.map(function(x){return esc(x.partnerStem+'＝'+x.tenGod);}).join('・')+'</p></section>'+ 
    '<section class="bzs-card"><h3>五行互補與負荷候選</h3><dl class="bzs-kv"><dt>B支持A</dt><dd>'+esc(c.elementComplement.partnerMaySupportA.join('、')||'無明顯項')+'</dd><dt>A支持B</dt><dd>'+esc(c.elementComplement.partnerMaySupportB.join('、')||'無明顯項')+'</dd><dt>B加重A</dt><dd>'+esc(c.elementComplement.partnerMayLoadA.join('、')||'無明顯項')+'</dd><dt>A加重B</dt><dd>'+esc(c.elementComplement.partnerMayLoadB.join('、')||'無明顯項')+'</dd></dl><div class="bzs-note">'+esc(c.elementComplement.caveat)+'</div></section>'+ 
    '<section class="bzs-card"><h3>現行運勢同步</h3><p>A：'+esc(c.luckSynchronization.aCurrent?c.luckSynchronization.aCurrent.gz+' 至 '+c.luckSynchronization.aCurrent.endDateExclusive:'未判定')+'</p><p>B：'+esc(c.luckSynchronization.bCurrent?c.luckSynchronization.bCurrent.gz+' 至 '+c.luckSynchronization.bCurrent.endDateExclusive:'未判定')+'</p><div class="bzs-luck"><table><thead><tr><th>年度</th><th>A</th><th>B</th></tr></thead><tbody>'+c.luckSynchronization.years.map(function(x){return '<tr><td>'+x.year+'</td><td>'+esc(x.a?x.a.gz+'／'+x.a.level:'—')+'</td><td>'+esc(x.b?x.b.gz+'／'+x.b.level:'—')+'</td></tr>';}).join('')+'</tbody></table></div></section>'+promptActions();}

  function resultPersonality(){var r=state.personality,p=r.profile;return '<section class="bzs-card bzs-type"><div class="code">'+esc(p.code)+'</div><h2>'+esc(p.name)+'</h2><div class="axes">'+esc(p.traits.join('・'))+'</div></section>'+summaryCard(r.chart,r.meta,'人格底層命盤')+'<section class="bzs-card"><h3>五軸來源</h3>'+p.axes.map(function(x){var right=x.rightSelected;return '<div class="bzs-axis"><span>'+esc(x.left)+'</span><div class="bzs-track"><i class="bzs-dot" style="left:'+(right?'calc(100% - 13px)':'0')+'"></i></div><span style="text-align:right">'+esc(x.right)+'</span></div><p style="font-size:11px;color:'+MUTED+'">'+esc(x.evidence)+'</p>';}).join('')+'</section><section class="bzs-card"><h3>可用優勢</h3><div class="bzs-tags">'+p.strengths.map(function(x){return '<span class="bzs-tag support">'+esc(x)+'</span>';}).join('')+'</div><h3 style="margin-top:15px">需要留意</h3><div class="bzs-tags">'+p.watch.map(function(x){return '<span class="bzs-tag tension">'+esc(x)+'</span>';}).join('')+'</div><div class="bzs-note warning" style="margin-top:12px">'+esc(p.disclaimer)+'</div></section>'+promptActions();}

  function loadHistory(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||'[]');}catch(e){return[];}}
  function saveHistory(item){try{var h=loadHistory();h.unshift(item);h=h.slice(0,30);localStorage.setItem(STORE_KEY,JSON.stringify(h));}catch(e){}}
  function renderHistory(){var h=loadHistory();if(!h.length)return icon('尚無分析紀錄','完成單盤、合盤或人格卡後，會在此保留最多30筆本機紀錄。');return '<section class="bzs-card"><h2>本機分析紀錄</h2><p>只保存在這台瀏覽器的 localStorage，可重新載入提示詞；不會上傳到本站伺服器。</p></section>'+h.map(function(x,i){return '<section class="bzs-card bzs-history"><div class="bzs-history-main"><h3>'+esc(x.title)+'</h3><time>'+esc(x.time)+'</time><p>'+esc(x.summary)+'</p><button class="bzs-action" data-history-open="'+i+'">載入提示詞</button></div><button title="刪除" data-history-delete="'+i+'">×</button></section>';}).join('')+'<button class="bzs-primary" data-act="clear-history">清除全部紀錄</button>';}

  function afterRender(){['s','a','b','p','u'].forEach(function(prefix){if(byId(prefix+'-country'))populateLocations(prefix);});document.querySelectorAll('#bzs-screen [data-ai]').forEach(function(a){a.addEventListener('click',function(){copyText(state.prompt,false);});});}
  function captureDraft(prefix){var country=byId(prefix+'-country');if(!country)return;drafts[prefix]={name:(byId(prefix+'-name')||{}).value||'',gender:(byId(prefix+'-gender')||{}).value||'male',date:(byId(prefix+'-date')||{}).value||'',time:(byId(prefix+'-time')||{}).value||'12:00',unknown:!!((byId(prefix+'-unknown')||{}).checked),country:country.value||'TW',city:(byId(prefix+'-city')||{}).value||'',boundary:(byId(prefix+'-boundary')||{}).value||'ZI_HOUR_23',question:(byId(prefix==='s'?'s-question':prefix==='p'?'p-question':'c-question')||{}).value||''};}
  function cacheAllForms(){['s','a','b','p','u'].forEach(captureDraft);}
  function restoreDraft(prefix){var d=drafts[prefix];if(!d)return;['name','gender','date','time','boundary'].forEach(function(k){var el=byId(prefix+'-'+k);if(el&&d[k]!=null)el.value=d[k];});var u=byId(prefix+'-unknown');if(u){u.checked=!!d.unknown;var t=byId(prefix+'-time');if(t){t.disabled=!!d.unknown;t.style.opacity=d.unknown?'.45':'1';}}var qid=prefix==='s'?'s-question':prefix==='p'?'p-question':'c-question',q=byId(qid);if(q&&d.question)q.value=d.question;}
  function populateLocations(prefix){var c=byId(prefix+'-country');if(!c||!window.BIRTH_CITIES)return;var d=drafts[prefix]||{},keys=Object.keys(BIRTH_CITIES),sorted=['TW'].concat(keys.filter(function(x){return x!=='TW';}));c.innerHTML='<option value="">選擇國家／地區</option>'+sorted.map(function(k){var x=BIRTH_CITIES[k];return '<option value="'+k+'">'+esc(x.flag+' '+x.name)+'</option>';}).join('');c.value=d.country||'TW';fillCities(prefix,c.value,'台南',d.city);restoreDraft(prefix);}
  function fillCities(prefix,cc,defaultCity,selectedIndex){var s=byId(prefix+'-city'),data=window.BIRTH_CITIES&&BIRTH_CITIES[cc];if(!s)return;s.innerHTML='<option value="">選擇城市</option>'+(data?data.cities.map(function(x,i){return '<option value="'+i+'">'+esc(x[0])+'</option>';}).join(''):'');if(selectedIndex!==undefined&&selectedIndex!==null&&selectedIndex!=='')s.value=String(selectedIndex);else if(data&&defaultCity){var idx=data.cities.findIndex(function(x){return x[0]===defaultCity;});if(idx>=0)s.value=String(idx);}}
  function getLocation(prefix){var cc=byId(prefix+'-country').value,ci=byId(prefix+'-city').value,data=window.BIRTH_CITIES&&BIRTH_CITIES[cc];if(!data||ci==='')throw new Error('請選擇出生國家與城市');var x=data.cities[Number(ci)];if(!x)throw new Error('出生城市資料無效');var tzMap=window.BIRTH_CITY_TIMEZONE_IDS||{};return {country:data.name,city:x[0],longitude:x[1],latitude:x[2],timezone:x[3],timezoneId:x[4]||tzMap[x[0]]||null,label:data.flag+' '+data.name+' '+x[0]};}

  function ensureRuntime(){return new Promise(function(resolve,reject){var checks=function(){return typeof window.calcTrueSolarTime==='function'&&typeof window.computeBazi==='function'&&typeof window.enhanceBazi==='function'&&window.BaziSuiteCore;};if(checks()){resolve();return;}var files=[];if(typeof window.Solar==='undefined')files.push('JS/vendor/lunar.js?v=1.7.7');if(!window.BaziCalendarCore)files.push('JS/bazi-calendar-core.js?v=20260625v1_0_0');if(typeof window.calcTrueSolarTime!=='function')files.push('JS/solar-location.js?v=20260625v18_2');if(typeof window.computeBazi!=='function')files.push('JS/bazi.js?v=20260625v44');if(typeof window.enhanceBazi!=='function')files.push('JS/bazi_upgrade.js?v=20260625v80_37');var i=0;function next(){if(i>=files.length){setTimeout(function(){checks()?resolve():reject(new Error('八字引擎載入失敗，請重新整理頁面'));},60);return;}var s=document.createElement('script');s.src=files[i++];s.onload=next;s.onerror=function(){reject(new Error('無法載入 '+s.src));};document.body.appendChild(s);}next();});}

  function readPerson(prefix){var date=byId(prefix+'-date').value,time=byId(prefix+'-time').value,unknown=byId(prefix+'-unknown').checked,name=byId(prefix+'-name').value.trim(),gender=byId(prefix+'-gender').value,boundary=byId(prefix+'-boundary').value;if(!date)throw new Error('請填寫出生日期');if(!unknown&&!time)throw new Error('請填寫出生時間，或勾選不知道時辰');var dp=date.split('-').map(Number),tp=(unknown?'12:00':time).split(':').map(Number),loc=getLocation(prefix);return {name:name,gender:gender,genderLabel:gender==='male'?'男命':'女命',year:dp[0],month:dp[1],day:dp[2],hour:tp[0],minute:tp[1],unknown:unknown,boundary:boundary,location:loc};}
  function calculatePerson(input){var l=input.location;var solar=calcTrueSolarTime(input.year,input.month,input.day,input.hour,input.minute,l.longitude,l.timezone,l.timezoneId);var b=computeBazi(solar.year,solar.month,solar.day,solar.hour,solar.minute,input.gender,{second:solar.second||0,trueSolarTimeApplied:true,timezoneId:l.timezoneId||null,timezoneOffset:l.timezone,longitude:l.longitude,dayBoundaryMode:input.boundary,referenceDate:new Date().toISOString()});enhanceBazi(b);var meta={name:input.name,gender:input.gender,genderLabel:input.genderLabel,unknown:input.unknown,solarInfo:solar,longitude:l.longitude,timezoneId:l.timezoneId,birthLine:'國曆 '+input.year+'/'+String(input.month).padStart(2,'0')+'/'+String(input.day).padStart(2,'0')+' '+(input.unknown?'時辰未知（12:00暫排）':String(input.hour).padStart(2,'0')+':'+String(input.minute).padStart(2,'0'))+'・'+l.city};return {chart:b,meta:meta};}

  async function calcSolarTool(){try{busy(true);await ensureRuntime();var date=(byId('u-date')||{}).value,time=(byId('u-time')||{}).value;if(!date||!time)throw new Error('請填寫民用日期與時間');var dp=date.split('-').map(Number),tp=time.split(':').map(Number),loc=getLocation('u');var r=calcTrueSolarTime(dp[0],dp[1],dp[2],tp[0],tp[1],loc.longitude,{timezone:loc.timezone,timezoneId:loc.timezoneId,second:tp[2]||0});r.inputCivilDateTime=date+' '+String(tp[0]).padStart(2,'0')+':'+String(tp[1]||0).padStart(2,'0')+':'+String(tp[2]||0).padStart(2,'0');r.inputLocation=loc;state.tools.solar=r;state.exportData={kind:'true-solar-time',location:loc,result:r};render();}catch(e){toast(e.message,true);}finally{busy(false);}}
  async function reverseBaziTool(){var progress=byId('r-progress');try{busy(true);if(progress)progress.style.display='block';await ensureRuntime();var opts={bazi:(byId('r-bazi')||{}).value,startYear:Number((byId('r-start')||{}).value),endYear:Number((byId('r-end')||{}).value),dayBoundaryMode:(byId('r-boundary')||{}).value,limit:Number((byId('r-limit')||{}).value)};var r=await BaziSuiteCore.reverseBaziToSolarTimesAsync(opts,function(){});state.tools.reverse=r;state.exportData={kind:'reverse-bazi',result:r};saveHistory({title:'反查｜'+r.query,time:new Date().toLocaleString(),summary:r.startYear+'～'+r.endYear+'｜找到 '+r.matches.length+' 個候選',prompt:JSON.stringify(r,null,2)});render();}catch(e){toast(e.message,true);}finally{busy(false);if(progress)progress.style.display='none';}}

  function busy(on){var buttons=document.querySelectorAll('#bzs-screen .bzs-primary');buttons.forEach(function(b){if(on){if(!b.dataset.originalLabel)b.dataset.originalLabel=b.textContent;b.disabled=true;b.textContent='正在校正與排盤…';}else{b.disabled=false;if(b.dataset.originalLabel){b.textContent=b.dataset.originalLabel;delete b.dataset.originalLabel;}}});}
  async function castSingle(){try{busy(true);await ensureRuntime();var x=calculatePerson(readPerson('s')),q=byId('s-question').value.trim();var prompt=BaziSuiteCore.buildSinglePrompt(state.lens,x.chart,x.meta,q);state.single={lens:state.lens,chart:x.chart,meta:x.meta};state.prompt=prompt;state.exportData={kind:'single',lens:state.lens,meta:x.meta,chart:x.chart,prompt:prompt};saveHistory({title:'單人｜'+BaziSuiteCore.lenses[state.lens].name,time:new Date().toLocaleString(),summary:x.meta.birthLine+'｜'+x.chart.pillars.year.gan+x.chart.pillars.year.zhi+' '+x.chart.pillars.month.gan+x.chart.pillars.month.zhi+' '+x.chart.pillars.day.gan+x.chart.pillars.day.zhi+' '+x.chart.pillars.hour.gan+x.chart.pillars.hour.zhi,prompt:prompt});render();}catch(e){toast(e.message,true);}finally{busy(false);}}
  async function castCompat(){try{busy(true);await ensureRuntime();var A=calculatePerson(readPerson('a')),B=calculatePerson(readPerson('b')),q=byId('c-question').value.trim();var comp=BaziSuiteCore.createCompatibility(A.chart,B.chart,{scenarioId:state.scenario,metaA:A.meta,metaB:B.meta});var prompt=BaziSuiteCore.buildCompatibilityPrompt(comp,q);state.compat={chartA:A.chart,chartB:B.chart,metaA:A.meta,metaB:B.meta,comp:comp};state.prompt=prompt;state.exportData={kind:'compatibility',metaA:A.meta,metaB:B.meta,compatibility:comp,prompt:prompt};saveHistory({title:'合盤｜'+comp.scenario.name,time:new Date().toLocaleString(),summary:A.meta.birthLine+' × '+B.meta.birthLine+'｜'+comp.evidenceSummary.signal,prompt:prompt});render();}catch(e){toast(e.message,true);}finally{busy(false);}}
  async function castPersonality(){try{busy(true);await ensureRuntime();var x=calculatePerson(readPerson('p')),q=byId('p-question').value.trim();var profile=BaziSuiteCore.buildPersonality(x.chart,x.meta),prompt=BaziSuiteCore.buildPersonalityPrompt(profile,q);state.personality={chart:x.chart,meta:x.meta,profile:profile};state.prompt=prompt;state.exportData={kind:'personality',meta:x.meta,profile:profile,prompt:prompt};saveHistory({title:'人格｜'+profile.name,time:new Date().toLocaleString(),summary:profile.code+'｜'+profile.traits.join('・'),prompt:prompt});render();}catch(e){toast(e.message,true);}finally{busy(false);}}

  function copyText(text,notify){if(!text)return Promise.reject(new Error('沒有可複製內容'));var p=navigator.clipboard&&navigator.clipboard.writeText?navigator.clipboard.writeText(text):new Promise(function(resolve,reject){try{var ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();resolve();}catch(e){reject(e);}});return p.then(function(){if(notify!==false)toast('已複製完整提示詞');}).catch(function(){toast('複製失敗，請長按文字手動複製',true);});}
  function download(name,text,type){var blob=new Blob([text],{type:type||'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
  function resetCurrent(){if(state.tab==='single')state.single=null;else if(state.tab==='compat')state.compat=null;else if(state.tab==='personality')state.personality=null;else if(state.tab==='tools')state.tools={solar:null,reverse:null};state.prompt='';state.exportData=null;render();}
  function sharePillars(chart){var P=chart&&chart.pillars||{};return ['year','month','day','hour'].map(function(k){var p=P[k]||{};return (p.gan||'')+(p.zhi||'');}).join(' ');}
  function shareCurrent(){
    var title=state.tab==='compat'?'八字情境合盤':state.tab==='personality'?'靜月五軸人格':'八字分析';
    var text=state.tab==='personality'&&state.personality?state.personality.profile.name+'｜'+state.personality.profile.code:state.tab==='compat'&&state.compat?state.compat.comp.scenario.name+'｜'+state.compat.comp.evidenceSummary.signal:'我的八字分析資料已完成';
    if(window.JYShareCard){
      if(state.tab==='personality'&&state.personality){var pp=state.personality.profile;JYShareCard.open('baziPersonality',{code:pp.code,name:pp.name,traits:pp.traits,strengths:pp.strengths,watch:pp.watch,birthLine:state.personality.meta.birthLine});return;}
      if(state.tab==='compat'&&state.compat){var cr=state.compat,c=cr.comp;JYShareCard.open('baziCompatibility',{scenario:c.scenario.name,nameA:cr.metaA.name||c.scenario.roleA,nameB:cr.metaB.name||c.scenario.roleB,pillarsA:sharePillars(cr.chartA),pillarsB:sharePillars(cr.chartB),dayPillars:c.spousePalace.aDayPillar+' × '+c.spousePalace.bDayPillar,signal:c.evidenceSummary.signal,support:c.evidenceSummary.supportCount,tension:c.evidenceSummary.tensionCount});return;}
      if(state.single){var sr=state.single,ch=sr.chart,P=ch.pillars||{},cur=arr(ch.dayun).find(function(x){return x.isCurrent;});JYShareCard.open('bazi',{question:BaziSuiteCore.lenses[sr.lens].name,pillars:['year','month','day','hour'].map(function(k,i){var p=P[k]||{};return {label:['年柱','月柱','日柱','時柱'][i],gan:p.gan||'',zhi:p.zhi||''};}),dayMaster:(ch.dm||'')+(ch.dmEl?'（'+ch.dmEl+'）':'')+'・'+fmt(ch.strongLevel),yongShen:arr(ch.wuxingStance&&ch.wuxingStance.xi||ch.fav).join('、'),dayun:cur?cur.gz+'（'+cur.startDate+'～'+cur.endDateExclusive+'）':''});return;}
    }
    if(navigator.share)navigator.share({title:title,text:text}).catch(function(){});else copyText(text,true);
  }

  function onClick(e){var tab=e.target.closest('[data-tab]');if(tab){state.tab=tab.dataset.tab;render();return;}var lens=e.target.closest('[data-lens]');if(lens){state.lens=lens.dataset.lens;render();return;}var sc=e.target.closest('[data-scenario]');if(sc){state.scenario=sc.dataset.scenario;render();return;}var ho=e.target.closest('[data-history-open]');if(ho){var item=loadHistory()[Number(ho.dataset.historyOpen)];if(item){state.prompt=item.prompt;state.exportData={kind:'history',prompt:item.prompt};copyText(item.prompt,true);}return;}var hd=e.target.closest('[data-history-delete]');if(hd){var h=loadHistory();h.splice(Number(hd.dataset.historyDelete),1);localStorage.setItem(STORE_KEY,JSON.stringify(h));render();return;}var a=e.target.closest('[data-act]');if(!a)return;switch(a.dataset.act){case'close':close();break;case'legacy':close();if(legacyOpen)legacyOpen();break;case'cast-single':castSingle();break;case'cast-compat':castCompat();break;case'cast-personality':castPersonality();break;case'calc-solar':calcSolarTool();break;case'reverse-bazi':reverseBaziTool();break;case'download-tool-json':download('bazi-tool-'+Date.now()+'.json',JSON.stringify(state.exportData,null,2),'application/json;charset=utf-8');break;case'clear-tools':state.tools={solar:null,reverse:null};state.exportData=null;render();break;case'copy':copyText(state.prompt,true);break;case'download-prompt':download('bazi-prompt-'+Date.now()+'.txt',state.prompt);break;case'download-json':download('bazi-data-'+Date.now()+'.json',JSON.stringify(state.exportData,null,2),'application/json;charset=utf-8');break;case'print':window.print();break;case'share':shareCurrent();break;case'reset-current':resetCurrent();break;case'clear-history':if(confirm('確定清除本機八字分析紀錄？')){localStorage.removeItem(STORE_KEY);render();}break;}}
  function onInput(e){if(e.target&&e.target.id){var p=e.target.id.split('-')[0];if(['s','a','b','p','u'].indexOf(p)>=0)captureDraft(p);}}
  function onChange(e){var country=e.target.closest('[data-country]');if(country){fillCities(country.dataset.country,country.value,'');captureDraft(country.dataset.country);return;}if(e.target.id&&/-unknown$/.test(e.target.id)){var prefix=e.target.id.split('-')[0],time=byId(prefix+'-time');if(time){time.disabled=e.target.checked;time.style.opacity=e.target.checked?'.45':'1';}captureDraft(prefix);}else if(e.target.id){var p=e.target.id.split('-')[0];if(['s','a','b','p','u'].indexOf(p)>=0)captureDraft(p);}}

  function open(){state.tab='single';state.single=null;state.compat=null;state.personality=null;state.tools={solar:null,reverse:null};state.prompt='';state.exportData=null;var s=getScreen();s.style.display='block';document.body.style.overflow='hidden';render();}
  function close(){if(screen)screen.style.display='none';document.body.style.overflow='';}

  // 保留原版八字單盤作為預設入口；完整套件改用獨立公開入口。
  // 先前直接覆蓋 window._baziStandaloneOpen，會讓原版自訂日期／時間／地點選擇器消失，
  // 並因 <input type="date/time"> 觸發 Android 系統日曆。此處不再覆蓋原入口。
  window._baziLegacyStandaloneOpen=legacyOpen;
  window._baziFullSuiteOpen=open;
  window._baziStandaloneOpen=legacyOpen || open;
  window.BaziSuiteUI={open:open,close:close,version:'1.0.1',getState:function(){return state;}};
})();
