#!/usr/bin/env python3
"""Build the offline name dictionary from versioned Unicode Unihan archives.

Usage: python scripts/build-name-data.py --unihan14 /path/Unihan-14.0.0.zip
       --unihan17 /path/Unihan-17.0.0.zip [--check]
No network, heuristic stroke fallback, or simplified/traditional conversion.
"""
import argparse, hashlib, json, pathlib, re, unicodedata, zipfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('--unihan14', required=True)
p.add_argument('--unihan17', required=True)
p.add_argument('--check', action='store_true')
a = p.parse_args()

def read(path, fields):
    out = {}
    with zipfile.ZipFile(path) as z:
        for filename in z.namelist():
            if not filename.endswith('.txt'): continue
            for line in z.read(filename).decode('utf-8').splitlines():
                if not line.startswith('U+'): continue
                cp, prop, value = line.split('\t', 2)
                if prop in fields: out.setdefault(chr(int(cp[2:], 16)), {})[prop] = value
    return out

old = read(a.unihan14, {'kRSKangXi'})
new = read(a.unihan17, {'kRSUnicode', 'kTotalStrokes', 'kAlternateTotalStrokes', 'kMandarin', 'kDefinition', 'kXHC1983', 'kHanyuPinlu'})
ends = [6,29,60,94,117,146,166,175,186,194,200,204,208,210,211,213,214]
radicals = [unicodedata.normalize('NFKC', chr(0x2F00+i)) for i in range(214)]
def radical_strokes(n): return next(i+1 for i,e in enumerate(ends) if n <= e)
rows = {}
ambiguous = 0
for ch in sorted(new.keys() | old.keys(), key=ord):
    props, earlier = new.get(ch, {}), old.get(ch, {})
    totals = set()
    for token in earlier.get('kRSKangXi','').split():
        m = re.fullmatch(r'(\d+)\.(-?\d+)',token)
        if m and 1 <= int(m[1]) <= 214:
            total = radical_strokes(int(m[1])) + int(m[2])
            if total > 0: totals.add(total)
    kangxi = next(iter(totals)) if len(totals)==1 else None
    if len(totals)>1: ambiguous += 1
    modern_values = [int(v) for v in props.get('kTotalStrokes','').split() if v.isdigit()]
    # Legacy two values are China, Taiwan; modern alternate IRG_T is explicit.
    modern = modern_values[-1] if modern_values else None
    for value, locations in re.findall(r'(\d+):([A-Z]+)',props.get('kAlternateTotalStrokes','')):
        if 'T' in locations: modern = int(value)
    tokens = props.get('kRSUnicode','').split()
    r = re.match(r'(\d+)', tokens[0]) if tokens else None
    radical = radicals[int(r[1])-1] if r and 1<=int(r[1])<=214 else ''
    alternatives = set()
    for entry in props.get('kXHC1983','').split():
        if ':' in entry: alternatives.update(entry.split(':',1)[1].split(','))
    alternatives.update(re.findall(r'([^\s()]+)\(\d+\)',props.get('kHanyuPinlu','')))
    alternatives.difference_update(props.get('kMandarin','').split())
    rows[ch] = [kangxi, modern, radical, props.get('kMandarin',''), props.get('kDefinition',''), earlier.get('kRSKangXi',''), ' '.join(sorted(alternatives))]

meta = {
    'version':'20261001-name1', 'characters':len(rows),
    'kangxiResolved':sum(r[0] is not None for r in rows.values()),
    'modernResolved':sum(r[1] is not None for r in rows.values()),
    'kangxiAmbiguous':ambiguous,
    'kangxiPolicy':'Unicode 14.0.0 kRSKangXi 的康熙部首原筆畫＋餘筆畫；多條分類僅在總數相同時採用。這是可核的部首還原口徑，未宣稱逐字核對康熙原書。',
    'modernPolicy':'Unicode 17.0.0 kTotalStrokes；有台灣 IRG_T alternate 時優先，否則標作 Unicode 現代筆畫，未宣稱教育部逐字核對。',
    'unknownPolicy':'無康熙資料、多候選總數不同或未知字不以現代筆畫猜算；允許使用者核對後覆核。',
    'sources':[
        {'url':'https://www.unicode.org/Public/14.0.0/ucd/Unihan.zip','sha256':hashlib.sha256(pathlib.Path(a.unihan14).read_bytes()).hexdigest()},
        {'url':'https://www.unicode.org/Public/17.0.0/ucd/Unihan.zip','sha256':hashlib.sha256(pathlib.Path(a.unihan17).read_bytes()).hexdigest()},
        {'url':'https://www.unicode.org/reports/tr38/','note':'kRSKangXi 已於15.1移除，因此本版使用可再現的14.0快照；現代筆畫不是康熙姓名筆畫。'}
    ], 'license':'Unicode License V3; see data/name/UNICODE-LICENSE.txt'
}
data = {'meta':meta,'fields':['kangxi','modern','radical','mandarin','definitionEnglish','kangxiRadicalResidual','dictionaryMandarinAlternates'],'characters':rows}
tables = json.loads((ROOT/'data/name/traditional-tables.json').read_text())
# Scores from the old shape-rule table are deliberately not exported.
for rules in tables['ZODIAC_NAME_DB'].values():
    for side in ('like','dislike'):
        for rule in rules[side]: rule.pop('score',None)
data['traditional'] = tables
data['numerology'] = json.loads((ROOT/'data/name/numerology-81.json').read_text())
body = '/* Generated by scripts/build-name-data.py; Unicode License V3. */\n(function(root){"use strict";root.JYNameData='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';if(typeof module==="object"&&module.exports)module.exports=root.JYNameData;})(globalThis);\n'
outputs = {'JS/name-data.js':body,'data/name/sources.json':json.dumps(meta,ensure_ascii=False,indent=2)+'\n'}
for file, text in outputs.items():
    dest = ROOT/file
    if a.check:
        if not dest.exists() or dest.read_text()!=text: raise SystemExit('Stale generated name data: '+file)
    else: dest.write_text(text)
print(json.dumps({k:meta[k] for k in ('characters','kangxiResolved','modernResolved','kangxiAmbiguous')},ensure_ascii=False))
